### Cabe aclarar que el puerto puede variar según su configuración; en este caso, se está utilizando el 3000.
### Para obtener más información sobre las rutas de la API, consulta el archivo "README.md".

### Ruta principal (Devuelve un mensaje de bienvenida y un poco de información sobre la API).
GET http://localhost:3000/

### Obtener todos los contenidos.
GET http://localhost:3000/contenido

### Obtener un contenido por ID.
GET http://localhost:3000/contenido/23

### Filtrar contenidos por título, género o categoría (búsqueda parcial).
### Por título:
GET http://localhost:3000/contenido/filtrar?titulo=it - capitulo
### Por género:
GET http://localhost:3000/contenido/filtrar?genero=comedia 
### Por categoría:
GET http://localhost:3000/contenido/filtrar?categoria=peli
### Filtrar por múltiples criterios a la vez (de manera conjunta):
GET http://localhost:3000/contenido/filtrar?titulo=Mandalorian&genero=Sci-Fi&categoria=Serie

### Agregar un nuevo contenido (película o serie), en este caso se agrega una serie por eso duración: null, ya que este campo es para películas.
POST http://localhost:3000/contenido
content-type: application/json

{
    "titulo": "Seinfeld",
    "resumen": "Cuatro amigos solteros, el comediante Jerry Seinfeld, el torpe George Constanza, la trabajadora frustrada Elaine Benes y el excéntrico vecino Cosmo Kramer, lidian con las vicisitudes diarias de la vida en la ciudad de Nueva York.",
    "temporadas": 9,
    "duracion": null, 
    "trailer": "https://www.youtube.com/watch?v=hQXKyIG_NS4",
    "idCategoria": 1,
    "generos": [12, 4],
    "actores": [836, 837, 838, 839]
}


### Actualizar parcialmente un contenido por su ID.
PATCH  http://localhost:3000/contenido/23
content-type: application/json

{
    "temporadas": 6
}

### Eliminar un contenido por su ID.
DELETE http://localhost:3000/contenido/103