USE trailerflix;

-- Insertar las categorías.
INSERT INTO categorias (nombre) VALUES
('Serie'),
('Película');

-- Insertar géneros.
INSERT INTO generos (nombre) VALUES
('Sci-Fi'),
('Fantasía'),
('Acción'),
('Drama'),
('Ficción'),
('Sucesos'),
('Misterio'),
('Suceso Real'),
('Crimen'),
('Suspenso'),
('Aventura'),
('Comedia'),
('Familia'),
('Western'),
('Tecnología'),
('Futurista'),
('Terror'),
('Historia'),
('Intriga'),
('¿Ficción?'),
('Ciencia ficción'),
('Romance'),
('Música'),
('Musical'),
('Animación');

-- Insertar actores.
INSERT INTO actores (nombre, apellido) VALUES
('Pedro', 'Pascal'),
('Carl', 'Weathers'),
('Misty', 'Rosas'),
('Chris', 'Bartlett'),
('Rio', 'Hackford'),
('Giancarlo', 'Esposito'),
('Tom', 'Hopper'),
('David', 'Castañeda'),
('Emmy', 'Raver-Lampman'),
('Robert', 'Sheehan'),
('Aidan', 'Gallagher'),
('Elliot', 'Page'),
('Anya', 'Taylor-Joy'),
('Thomas', 'Brodie-Sangster'),
('Harry', 'Melling'),
('Moses', 'Ingram'),
('Chloe', 'Pirrie'),
('Janina', 'Elkin'),
('Lili', 'Reinhart'),
('Casey', 'Cott'),
('Camila', 'Mendes'),
('Marisol', 'Nichols'),
('Madelaine', 'Petsch'),
('Mädchen', 'Amick'),
('Claire', 'Fox'),
('Olivia', 'Colman'),
('Matt', 'Smith'),
('Tobias', 'Menzies'),
('Vanesa', 'Kirby'),
('Helena', 'Bonham Carter'),
('Millie', 'Bobby Brown'), -------
('Gaten', 'Matarazzo'),
('Henry', 'Cavill'),
('Sam', 'Claflin'),
('Louis', 'Partridge'),
('Adeel', 'Akhtar'),
('Joaquin', 'Phoenix'),
('Robert', 'De Niro'),
('Zazie', 'Beetz'),
('Frances', 'Conroy'),
('Brett', 'Cullen'),
('Shea', 'Whigham'),
('Robert', 'Downey Jr.'),
('Chris', 'Evans'),
('Mark', 'Ruffalo'),
('Chris', 'Hemsworth'), ---
('Jeremy', 'Renner'),
('Emilia', 'Clarke'),
('Lena', 'Headey'),
('Sophie', 'Turner'),
('Kit', 'Harington'),
('Peter', 'Dinklage'),
('Nikolaj', 'Coster-Waldau'),
('Grant', 'Gustin'),
('Carlos', 'Valdes'),
('Danielle', 'Panabaker'),
('Candice', 'Patton'),
('Jesse', 'L. Martin'),
('Tom', 'Cavanagh'),
('Jim', 'Parsons'),
('Johnny', 'Galecki'),
('Kaley', 'Cuoco'),
('Simon', 'Helberg'),
('Kunal', 'Nayyar'),
('Melissa', 'Rauch'),
('Mayim', 'Bialik'),
('Jennifer', 'Aniston'),
('Courteney', 'Cox'),
('Lisa', 'Kudrow'),
('David', 'Schwimmer'),
('Matthew', 'Perry'),
('Matt', 'LeBlanc'),
('Amybeth', 'McNulty'),
('Geraldine', 'James'),
('R. H.', 'Thomson'),
('Corrine', 'Koslo'),
('Dalila', 'Bela'),
('Lucas', 'Jade Zumann'),
('Gillian', 'Anderson'),
('David', 'Duchovny'),
('Mitch', 'Pileggi'),
('Robert', 'Patrick'),
('Tom', 'Braidwood'),
('Bruce', 'Harwood'),
('Jared', 'Harris'),
('Stellan', 'Skarsgård'),
('Emily', 'Watson'),
('Paul', 'Ritter'),
('Jessie', 'Buckley'),
('Adam', 'Nagaitis'),
('Evan', 'Rachel Wood'),
('Thandiwe', 'Newton'),
('Jeffrey', 'Wright'),
('Tessa', 'Thompson'),
('Ed', 'Harris'),
('Luke', 'Hemsworth'),
('Rodrigo', 'Santoro'),
('Simon', 'Quarterman'),
('Clifton', 'Collins Jr.'),
('Anthony', 'Hopkins'),
('Ingrid', 'Bolsø Berdal'),
('Angela', 'Sarafyan'),
('Shannon', 'Woodward'),
('Talulah', 'Riley'),
('Louis', 'Herthum'),
('Ben', 'Barnes'),
('Jimmi', 'Simpson'),
('Leonardo', 'Nam'),
('Aaron', 'Paul'),
('Vincent', 'Cassel'),
('Izabella', 'Alvarez'),
('Jeff', 'Daniel Phillips'),
('Lee', 'Pace'),
('Scoot', 'McNairy'),
('Mackenzie', 'Davis'),
('Kerry', 'Bishé'),
('Toby', 'Huss'),
('Alana', 'Cavanaugh'),
('Jessica', 'Chastain'),
('John', 'Malkovich'),
('Colin', 'Farrell'),
('Geena', 'Davis'),
('Ioan', 'Gruffudd'),
('Margot', 'Robbie'),
('Ewan', 'McGregor'),
('Mary', 'Elizabeth Winstead'),
('Jurnee', 'Smollett'),
('Rosie', 'Perez'),
('Chris', 'Messina'),
('Stacy', 'Martin'),
('Rhona', 'Mitra'),
('Theo', 'James'),
('Peter', 'Ferdinando'),
('Lia', 'Williams'),
('Toby', 'Jones'),
('Miranda', 'Cosgrove'),
('Kate', 'Walsh'),
('Omar', 'Epps'),
('Angus', 'Macfadyen'),
('Jorja', 'Fox'),
('Enver', 'Gjokaj'),
('Bill', 'Skarsgård'),
('Jessica', 'Chastain'),
('Bill', 'Hader'),
('James', 'McAvoy'),
('Isaiah', 'Mustafa'),
('Jay', 'Ryan'),
('Chadwick', 'Boseman'),
('Michael', 'B. Jordan'),
('Lupita', 'Nyong\'o'),
('Danai', 'Gurira'),
('Martin', 'Freeman'),
('Daniel', 'Kaluuya'),
('Christian', 'Bale'),
('Matt', 'Damon'),
('Caitriona', 'Balfe'),
('Josh', 'Lucas'),
('Noah', 'Jupe'),
('Jon', 'Bernthal'),
('Génesis', 'Rodríguez'),
('Vincent', 'Piazza'),
('Benjamin', 'Sokolow'),
('Emily', 'Bayiokos'),
('Amy', 'Manson'),
('Luke', 'Allen-Gale'),
('Nina', 'Bergman'),
('Dominic', 'Mafham'),
('James', 'Weber Brown'),
('Lorina', 'Kamburova'),
('Marion', 'Cotillard'),
('Jude', 'Law'),
('Kate', 'Winslet'),
('Jennifer', 'Ehle'),
('Gwyneth', 'Paltrow'),
('Scarlett', 'Johansson'),
('Florence', 'Pugh'),
('David', 'Harbour'),
('O.T.', 'Fagbenle'),
('Rachel', 'Weisz'),
('William', 'Hurt'),
('Ray', 'Winstone'),
('Jessica', 'Chastain'),
('Kristen', 'Wiig'),
('Jeff', 'Daniels'),
('Michael', 'Peña'),
('Sean', 'Bean'),
('Kate', 'Mara'),
('Alicia', 'Vikander'),
('Domhnall', 'Gleeson'),
('Oscar', 'Isaac'),
('Sonoya', 'Mizuno'),
('Corey', 'Johnson'),
('Claire', 'Selby'),
('Gana', 'Bayarsaikhan'),
('Bryce', 'Dallas Howard'),
('Chris', 'Pratt'),
('Irrfan', 'Khan'),
('Omar', 'Sy'),
('Nick', 'Robinson'),
('Judy', 'Greer'),
('Will', 'Smith'),
('Alice', 'Braga'),
('Charlie', 'Tahan'),
('Dash', 'Mihok'),
('Salli', 'Richardson-Whitfield'),
('Willow', 'Smith'),
('Emma', 'Thompson'),
('Ryan', 'Gosling'),
('Claire', 'Foy'),
('Jason', 'Clarke'),
('Kyle', 'Chandler'),
('Corey', 'Stoll'),
('Patrick', 'Fugit'),
('John', 'Boyega'),
('Scott', 'Eastwood'),
('Cailee', 'Spaeny'),
('Jing', 'Tian'),
('Rinko', 'Kikuchi'),
('Burn', 'Gorman'),
('Ashton', 'Kutcher'),
('Dermot', 'Mulroney'),
('Josh', 'Gad'),
('Lukas', 'Haas'),
('Matthew', 'Modine'),
('J.K.', 'Simmons'),
('Lesley', 'Ann Warren'),
('Noah', 'Wyle'),
('Anthony', 'Michael'),
('Joey', 'Slotnick'),
('J.G.', 'Hertzler'),
('Wayne', 'Pére'),
('Sheila', 'Shaw'),
('Gemma', 'Zamprogna'),
('John', 'DiMaggio'),
('Jesse', 'Eisenberg'),
('Andrew', 'Garfield'),
('Justin', 'Timberlake'),
('Armie', 'Hammer'),
('Max', 'Minghella'),
('Rooney', 'Mara'),
('Brenda', 'Song'),
('Rashida', 'Jones'),
('John', 'Gertz'),
('Ryan', 'Phillippe'),
('Rachael', 'Leigh Cook'),
('Tim', 'Robbins'),
('Claire', 'Forlani'),
('Richard', 'Rountree'),
('Tygh', 'Runyan'),
('Ned', 'Bellamy'),
('Tyler', 'Labine'),
('Anna', 'Kendrick'),
('Daniel', 'Dae Kim'),
('Shamier', 'Anderson'),
('Toni', 'Collette'),
('Ben', 'Affleck'),
('Henry', 'Cavill'),
('Gal', 'Gadot'),
('Jason', 'Momoa'),
('Ezra', 'Miller'),
('Ray', 'Fisher'),
('Amy', 'Adams'),
('Jeremy', 'Irons'),
('Connie', 'Nielsen'),
('Charlie', 'Sheen'),
('Jon', 'Cryer'),
('Angus T.', 'Jones'),
('Conchata', 'Ferrel'),
('Holland', 'Taylor'),
('Marin', 'Hinkle'),
('Jennifer', 'Bini Taylor'),
('Melanie', 'Lynskey'),
('Amber', 'Tamblyn'),
('Úrsula', 'Corberó'),
('Álvaro', 'Morte'),
('Itziar', 'Ituño'),
('Pedro', 'Alonso'),
('Alba', 'Flores'),
('Miguel', 'Herrán'),
('Jaime', 'Lorente'),
('Esther', 'Acebo'),
('Enrique', 'Arce'),
('Winona', 'Ryder'),
('Finn', 'Wolfhard'),
('Millie', 'Bobby Brown'), 
('Caleb', 'McLaughlin'),
('Natalia', 'Dyer'),
('Charlie', 'Heaton'), 
('Joe', 'Keery'),
('Sandra', 'Bullock'),
('George', 'Clooney'),
('Orto', 'Ignatiussen'), ---
('Phaldut', 'Sharma'),
('Amy', 'Warren'),
('Basher', 'Savage'),
('Adam', 'Cozens'),
('Jaeden', 'Martell'),
('Jeremy', 'Ray'),
('Sophia', 'Lillis'),
('Chosen', 'Jacobs'),
('Jack', 'Dylan Grazer'),
('Wyatt', 'Oleff'),
('Nicholas', 'Hamilton'),
('Tom', 'Hanks'),
('Bill', 'Paxton'),
('Kevin', 'Bacon'),
('Gary', 'Sinise'), ----
('Kathleen', 'Quinlan'),
('Roger', 'Corman'),
('Chris', 'Ellis'),
('Xander', 'Berkeley'),
('Liev', 'Schreiber'),
('Julia', 'Stiles'),
('Seamus', 'Davey-Fitzpatrick'),
('David', 'Thewlis'),
('Pete', 'Postlethwaite'),
('Mia', 'Farrow'),
('Predrag', 'Bjelac'),
('Carlo', 'Sabatini'),
('Amy', 'Huck'),
('Ellen', 'Burstyn'),
('Linda', 'Blair'),
('Max', 'von Sydow'),
('Lee', 'J. Cobb'),
('Kitty', 'Winn'),
('Jack', 'MacGowran'),
('Jason', 'Miller'),
('William', 'O\'Malley'),
('Barton', 'Heyman'),
('Rainn', 'Wilson'),
('Steve', 'Carell'),
('Jenna', 'Fischer'),
('John', 'Krasinski'),
('B.J.', 'Novak'),
('Kate', 'Flannery'),
('Brian', 'Baumgartner'),
('Leslie David', 'Baker'),
('Mindy', 'Kaling'),
('Angela', 'Kinsey'),
('Freddie', 'Highmore'),
('Antonia', 'Thomas'),
('Hill', 'Harper'),
('Richard', 'Schiff'),
('Christina', 'Chang'),
('Paige', 'Spara'),
('Fiona', 'Gubelmann'),
('Will', 'Yun Lee'),
('Nicholas', 'Gonzalez'),
('Eddie', 'Redmayne'),
('Felicity', 'Jones'),
('Charlie', 'Cox'),
('Emily', 'Watson'),
('Simon', 'McBurney'), --
('Maxine', 'Peake'),
('Harry', 'Lloyd'),
('Tom', 'Prior'),
('Benedict', 'Cumberbatch'),
('Keira', 'Knightley'), --
('Taraji P.', 'Henson'),
('Octavia', 'Spencer'),
('Janelle', 'Monáe'),
('Kevin', 'Costner'),
('Kirsten', 'Dunst'),
('Jim', 'Parsons'),
('Mahershala', 'Ali'),
('Glen', 'Powell'),
('Ariana', 'Neal'),
('Russell', 'Crowe'),
('Jennifer', 'Connelly'),
('Ed', 'Harris'),
('Paul', 'Bettany'),
('Christopher', 'Plummer'),
('Josh', 'Lucas'),
('Adam', 'Goldberg'),
('Anthony', 'Rapp'),
('Judd', 'Hirsch'),
('Jennifer', 'Lawrence'),
('Chris', 'Pratt'),
('Michael', 'Sheen'),
('Laurence', 'Fishburne'),
('Andy', 'García'),
('Aurora', 'Perrineau'),
('Kristin', 'Brock'),
('Julee', 'Cerda'),
('Fred', 'Melamed'),
('Anne', 'Hathaway'),
('Patrick', 'Wilson'),
('Andre', 'Braugher'),
('Dianne', 'Wiest'),
('David', 'Morse'),
('William', 'B. Davis'),
('Ryan', 'Robbins'),
('Clea', 'DuVall'),
('Don', 'Thompson'),
('Ben', 'Affleck'),
('Bryan', 'Cranston'),
('Alan', 'Arkin'),
('John', 'Goodman'),
('Victor', 'Garber'),
('Tate', 'Donovan'),
('Scoot', 'McNairy'),
('Rory', 'Cochrane'),
('Kerry', 'Bishé'),
('Noomi', 'Rapace'),
('Michael', 'Fassbender'),
('Charlize', 'Theron'),
('Logan', 'Marshall-Green'),
('Guy', 'Pearce'),
('Idris', 'Elba'),
('Sean', 'Harris'),
('Rafe', 'Spall'),
('Kate', 'Dickie'),
('Emut', 'Elliott'),
('Benedict', 'Wong'),
('Lucy', 'Hutchinson'),
('Patrick', 'Wilson'),
('Ian', 'Whyte'),
('Branwell', 'Donaghey'),
('Vladimir', 'Furdik'),
('C.C.', 'Smiff'),
('Shane', 'Steyn'),
('John', 'Lebar'),
('Jake', 'Gyllenhaal'),
('Rebecca', 'Ferguson'),
('Ryan', 'Reynolds'),
('Hiroyuki', 'Sanada'),
('Airyon', 'Bakare'),
('Olga', 'Dihovichnaya'),
('Naoko', 'Mori'),
('Haruka', 'Kuroda'),
('Camiel', 'Warren-Taylor'),
('Rosamund', 'Pike'),
('Sam', 'Riley'),
('Aneurin', 'Barnard'),
('Simon', 'Russell Beale'),
('Jonathan', 'Aris'),
('Tim', 'Woodward'),
('Katherine', 'Parkinson'),
('Chris', 'O\'Dowd'),
('Gragam', 'Linehan'),
('Richard', 'Ayoade'),
('Matt', 'Berry'),
('Tom', 'Binns'),
('Lewis', 'Macleod'),
('Noel', 'Fielding'),
('Peter', 'Serafinowicz'),
('Tuppence', 'Middleton'),
('Ian', 'Bonar'),
('Elisabeth', 'Hopper'),
('Nick', 'Bartlett'),
('Wunmi', 'Mosaku'),
('Alex', 'Lawther'),
('Jerome', 'Flynn'),
('Susannah', 'Doyle'),
('Madeline', 'Brewer'),
('Ariane', 'Labed'),
('Sarah', 'Snook'),
('Michael', 'Kelly'),
('Jola', 'Bokinni'),
('Faye', 'Marsay'),
('Ben', 'Wong'),
('Jonas', 'Karlsson'),
('Chloe', 'Pirrie'),
('Eugene', 'O\'Hare'),
('Indira', 'Ainger'),
('James', 'Lance'),
('David', 'Ajala'),
('Sarah', 'Abbott'),
('Clint', 'Dyer'),
('Jake', 'Davies'),
('Letitia', 'Wright'),
('Babs', 'Olusanmokun'),
('Georgina', 'Campbell'),
('Jesse', 'Plemons'),
('Jimmi', 'Simpson'),
('Aaron', 'Paul'),
('Aldis', 'Hodge'),
('Kiran', 'Sonia Sawar'),
('Miley', 'Cyrus'),
('Anthony', 'Mackie'),
('Nicole', 'Beharie'),
('Mackenzie', 'Davis'),
('Gugu', 'Mbatha-Raw'),
('Tom', 'Cruise'), 
('Jon', 'Voight'), 
('Emmanuelle', 'Béart'), 
('Henry', 'Czerny'), 
('Jean', 'Reno'), 
('Ving', 'Rhames'), 
('Kristin', 'Scott Thomas'), 
('Vanessa', 'Redgrave'), 
('Ingeborga', 'Dapkünaitè'),
('Armie', 'Hammer'),
('Elizabeth', 'Debicki'),
('Luca', 'Calvani'),
('Sylvester', 'Groth'),
('Misha', 'Kuznetsov'),
('Hugh', 'Grant'),
('Jared', 'Harris'),
('Christian', 'Berkel'),
('Dwayne', 'Johnson'),
('Kevin', 'Hart'),
('Jack', 'Black'),
('Karen', 'Gillan'),
('Nick', 'Jonas'),
('Rhys', 'Darby'),
('Bobby', 'Cannavale'),
('Alex', 'Wolff'),
('Ser\'Darius', 'Blain'),
('Madison', 'Iseman'),
('Morgan', 'Turner'),
('Sean', 'Buxton'),
('Mason', 'Guccione'),
('Guy', 'Williams'),
('Marianna', 'Di Martino'), --Hasta acá llegamos al ID 73 INCLUSIVE.
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
('', ''),
