USE trailerflix;

-- Insertar las categorías.
INSERT INTO categorias (nombre) VALUES
('Serie'),
('Película');

-- Insertar géneros.
INSERT INTO generos (nombre) VALUES
('Sci-Fi'),
('Fantasía'),
('Acción'),
('Drama'),
('Ficción'),
('Sucesos'),
('Misterio'),
('Suceso Real'),
('Crimen'),
('Suspenso'),
('Aventura'),
('Comedia'),
('Familia'),
('Western'),
('Tecnología'),
('Futurista'),
('Terror'),
('Historia'),
('Intriga'),
('¿Ficción?'),
('Ciencia ficción'),
('Romance'),
('Música'),
('Musical'),
('Animación');

-- Insertar actores.
INSERT INTO actores (nombre, apellido) VALUES
('Pedro', 'Pascal'),
('Carl', 'Weathers'),
('Misty', 'Rosas'),
('Chris', 'Bartlett'),
('Rio', 'Hackford'),
('Giancarlo', 'Esposito'),
('Tom', 'Hopper'),
('David', 'Castañeda'),
('Emmy', 'Raver-Lampman'),
('Robert', 'Sheehan'),
('Aidan', 'Gallagher'),
('Elliot', 'Page'),
('Anya', 'Taylor-Joy'),
('Thomas', 'Brodie-Sangster'),
('Harry', 'Melling'),
('Moses', 'Ingram'),
('Chloe', 'Pirrie'),
('Janina', 'Elkin'),
('Lili', 'Reinhart'),
('Casey', 'Cott'),
('Camila', 'Mendes'),
('Marisol', 'Nichols'),
('Madelaine', 'Petsch'),
('Mädchen', 'Amick'),
('Claire', 'Fox'),
('Olivia', 'Colman'),
('Matt', 'Smith'),
('Tobias', 'Menzies'),
('Vanesa', 'Kirby'),
('Helena', 'Bonham Carter'),
('Millie', 'Bobby Brown'), 
('Gaten', 'Matarazzo'),
('Henry', 'Cavill'),
('Sam', 'Claflin'),
('Louis', 'Partridge'),
('Adeel', 'Akhtar'),
('Joaquin', 'Phoenix'),
('Robert', 'De Niro'),
('Zazie', 'Beetz'),
('Frances', 'Conroy'),
('Brett', 'Cullen'),
('Shea', 'Whigham'),
('Robert', 'Downey Jr.'),
('Chris', 'Evans'),
('Mark', 'Ruffalo'),
('Chris', 'Hemsworth'), 
('Jeremy', 'Renner'),
('Emilia', 'Clarke'),
('Lena', 'Headey'),
('Sophie', 'Turner'),
('Kit', 'Harington'),
('Peter', 'Dinklage'),
('Nikolaj', 'Coster-Waldau'),
('Grant', 'Gustin'),
('Carlos', 'Valdes'),
('Danielle', 'Panabaker'),
('Candice', 'Patton'),
('Jesse', 'L. Martin'),
('Tom', 'Cavanagh'),
('Jim', 'Parsons'),
('Johnny', 'Galecki'),
('Kaley', 'Cuoco'),
('Simon', 'Helberg'),
('Kunal', 'Nayyar'),
('Melissa', 'Rauch'),
('Mayim', 'Bialik'),
('Jennifer', 'Aniston'),
('Courteney', 'Cox'),
('Lisa', 'Kudrow'),
('David', 'Schwimmer'),
('Matthew', 'Perry'),
('Matt', 'LeBlanc'),
('Amybeth', 'McNulty'),
('Geraldine', 'James'),
('R. H.', 'Thomson'),
('Corrine', 'Koslo'),
('Dalila', 'Bela'),
('Lucas', 'Jade Zumann'),
('Gillian', 'Anderson'),
('David', 'Duchovny'),
('Mitch', 'Pileggi'),
('Robert', 'Patrick'),
('Tom', 'Braidwood'),
('Bruce', 'Harwood'),
('Jared', 'Harris'),
('Stellan', 'Skarsgård'),
('Emily', 'Watson'),
('Paul', 'Ritter'),
('Jessie', 'Buckley'),
('Adam', 'Nagaitis'),
('Evan', 'Rachel Wood'),
('Thandiwe', 'Newton'),
('Jeffrey', 'Wright'),
('Tessa', 'Thompson'),
('Ed', 'Harris'),
('Luke', 'Hemsworth'),
('Rodrigo', 'Santoro'),
('Simon', 'Quarterman'),
('Clifton', 'Collins Jr.'),
('Anthony', 'Hopkins'),
('Ingrid', 'Bolsø Berdal'),
('Angela', 'Sarafyan'),
('Shannon', 'Woodward'),
('Talulah', 'Riley'),
('Louis', 'Herthum'),
('Ben', 'Barnes'),
('Jimmi', 'Simpson'),
('Leonardo', 'Nam'),
('Aaron', 'Paul'),
('Vincent', 'Cassel'),
('Izabella', 'Alvarez'),
('Jeff', 'Daniel Phillips'),
('Lee', 'Pace'),
('Scoot', 'McNairy'),
('Mackenzie', 'Davis'),
('Kerry', 'Bishé'),
('Toby', 'Huss'),
('Alana', 'Cavanaugh'),
('Jessica', 'Chastain'),
('John', 'Malkovich'),
('Colin', 'Farrell'),
('Geena', 'Davis'),
('Ioan', 'Gruffudd'),
('Margot', 'Robbie'),
('Ewan', 'McGregor'),
('Mary', 'Elizabeth Winstead'),
('Jurnee', 'Smollett'),
('Rosie', 'Perez'),
('Chris', 'Messina'),
('Stacy', 'Martin'),
('Rhona', 'Mitra'),
('Theo', 'James'),
('Peter', 'Ferdinando'),
('Lia', 'Williams'),
('Toby', 'Jones'),
('Miranda', 'Cosgrove'),
('Kate', 'Walsh'),
('Omar', 'Epps'),
('Angus', 'Macfadyen'),
('Jorja', 'Fox'),
('Enver', 'Gjokaj'),
('Bill', 'Skarsgård'),
('Bill', 'Hader'),
('James', 'McAvoy'),
('Isaiah', 'Mustafa'),
('Jay', 'Ryan'),
('Chadwick', 'Boseman'),
('Michael', 'B. Jordan'),
('Lupita', 'Nyong\'o'),
('Danai', 'Gurira'),
('Martin', 'Freeman'),
('Daniel', 'Kaluuya'),
('Christian', 'Bale'),
('Matt', 'Damon'),
('Caitriona', 'Balfe'),
('Josh', 'Lucas'),
('Noah', 'Jupe'),
('Jon', 'Bernthal'),
('Génesis', 'Rodríguez'),
('Vincent', 'Piazza'),
('Benjamin', 'Sokolow'),
('Emily', 'Bayiokos'),
('Amy', 'Manson'),
('Luke', 'Allen-Gale'),
('Nina', 'Bergman'),
('Dominic', 'Mafham'),
('James', 'Weber Brown'),
('Lorina', 'Kamburova'),
('Marion', 'Cotillard'),
('Jude', 'Law'),
('Kate', 'Winslet'),
('Jennifer', 'Ehle'),
('Gwyneth', 'Paltrow'),
('Scarlett', 'Johansson'),
('Florence', 'Pugh'),
('David', 'Harbour'),
('O.T.', 'Fagbenle'),
('Rachel', 'Weisz'),
('William', 'Hurt'),
('Ray', 'Winstone'),
('Kristen', 'Wiig'),
('Jeff', 'Daniels'),
('Michael', 'Peña'),
('Sean', 'Bean'),
('Kate', 'Mara'),
('Alicia', 'Vikander'),
('Domhnall', 'Gleeson'),
('Oscar', 'Isaac'),
('Sonoya', 'Mizuno'),
('Corey', 'Johnson'),
('Claire', 'Selby'),
('Gana', 'Bayarsaikhan'),
('Bryce', 'Dallas Howard'),
('Chris', 'Pratt'),
('Irrfan', 'Khan'),
('Omar', 'Sy'),
('Nick', 'Robinson'),
('Judy', 'Greer'),
('Will', 'Smith'),
('Alice', 'Braga'),
('Charlie', 'Tahan'),
('Dash', 'Mihok'),
('Salli', 'Richardson-Whitfield'),
('Willow', 'Smith'),
('Emma', 'Thompson'),
('Ryan', 'Gosling'),
('Claire', 'Foy'),
('Jason', 'Clarke'),
('Kyle', 'Chandler'),
('Corey', 'Stoll'),
('Patrick', 'Fugit'),
('John', 'Boyega'),
('Scott', 'Eastwood'),
('Cailee', 'Spaeny'),
('Jing', 'Tian'),
('Rinko', 'Kikuchi'),
('Burn', 'Gorman'),
('Ashton', 'Kutcher'),
('Dermot', 'Mulroney'),
('Lukas', 'Haas'),
('Matthew', 'Modine'),
('J.K.', 'Simmons'),
('Lesley', 'Ann Warren'),
('Noah', 'Wyle'),
('Anthony', 'Michael'),
('Joey', 'Slotnick'),
('J.G.', 'Hertzler'),
('Wayne', 'Pére'),
('Sheila', 'Shaw'),
('Gemma', 'Zamprogna'),
('John', 'DiMaggio'),
('Jesse', 'Eisenberg'),
('Andrew', 'Garfield'),
('Justin', 'Timberlake'),
('Armie', 'Hammer'),
('Max', 'Minghella'),
('Rooney', 'Mara'),
('Brenda', 'Song'),
('Rashida', 'Jones'),
('John', 'Gertz'),
('Ryan', 'Phillippe'),
('Rachael', 'Leigh Cook'),
('Tim', 'Robbins'),
('Claire', 'Forlani'),
('Richard', 'Rountree'),
('Tygh', 'Runyan'),
('Ned', 'Bellamy'),
('Tyler', 'Labine'),
('Anna', 'Kendrick'),
('Daniel', 'Dae Kim'),
('Shamier', 'Anderson'),
('Toni', 'Collette'),
('Ben', 'Affleck'),
('Jason', 'Momoa'),
('Ezra', 'Miller'),
('Ray', 'Fisher'),
('Amy', 'Adams'),
('Jeremy', 'Irons'),
('Connie', 'Nielsen'),
('Charlie', 'Sheen'),
('Jon', 'Cryer'),
('Angus T.', 'Jones'),
('Conchata', 'Ferrel'),
('Holland', 'Taylor'),
('Marin', 'Hinkle'),
('Jennifer', 'Bini Taylor'),
('Melanie', 'Lynskey'),
('Amber', 'Tamblyn'),
('Úrsula', 'Corberó'),
('Álvaro', 'Morte'),
('Itziar', 'Ituño'),
('Pedro', 'Alonso'),
('Alba', 'Flores'),
('Miguel', 'Herrán'),
('Jaime', 'Lorente'),
('Esther', 'Acebo'),
('Enrique', 'Arce'),
('Winona', 'Ryder'),
('Finn', 'Wolfhard'),
('Caleb', 'McLaughlin'),
('Natalia', 'Dyer'),
('Charlie', 'Heaton'), 
('Joe', 'Keery'),
('Sandra', 'Bullock'),
('George', 'Clooney'),
('Orto', 'Ignatiussen'), ---
('Phaldut', 'Sharma'),
('Amy', 'Warren'),
('Basher', 'Savage'),
('Adam', 'Cozens'),
('Jaeden', 'Martell'),
('Jeremy', 'Ray'),
('Sophia', 'Lillis'),
('Chosen', 'Jacobs'),
('Jack', 'Dylan Grazer'),
('Wyatt', 'Oleff'),
('Nicholas', 'Hamilton'),
('Tom', 'Hanks'),
('Bill', 'Paxton'),
('Kevin', 'Bacon'),
('Gary', 'Sinise'), ----
('Kathleen', 'Quinlan'),
('Roger', 'Corman'),
('Chris', 'Ellis'),
('Xander', 'Berkeley'),
('Liev', 'Schreiber'),
('Julia', 'Stiles'),
('Seamus', 'Davey-Fitzpatrick'),
('David', 'Thewlis'),
('Pete', 'Postlethwaite'),
('Mia', 'Farrow'),
('Predrag', 'Bjelac'),
('Carlo', 'Sabatini'),
('Amy', 'Huck'),
('Ellen', 'Burstyn'),
('Linda', 'Blair'),
('Max', 'von Sydow'),
('Lee', 'J. Cobb'),
('Kitty', 'Winn'),
('Jack', 'MacGowran'),
('Jason', 'Miller'),
('William', 'O\'Malley'),
('Barton', 'Heyman'),
('Rainn', 'Wilson'),
('Steve', 'Carell'),
('Jenna', 'Fischer'),
('John', 'Krasinski'),
('B.J.', 'Novak'),
('Kate', 'Flannery'),
('Brian', 'Baumgartner'),
('Leslie David', 'Baker'),
('Mindy', 'Kaling'),
('Angela', 'Kinsey'),
('Freddie', 'Highmore'),
('Antonia', 'Thomas'),
('Hill', 'Harper'),
('Richard', 'Schiff'),
('Christina', 'Chang'),
('Paige', 'Spara'),
('Fiona', 'Gubelmann'),
('Will', 'Yun Lee'),
('Nicholas', 'Gonzalez'),
('Eddie', 'Redmayne'),
('Felicity', 'Jones'),
('Charlie', 'Cox'),
('Simon', 'McBurney')
('Maxine', 'Peake'),
('Harry', 'Lloyd'),
('Tom', 'Prior'),
('Benedict', 'Cumberbatch'),
('Keira', 'Knightley'), 
('Taraji P.', 'Henson'),
('Octavia', 'Spencer'),
('Janelle', 'Monáe'),
('Kevin', 'Costner'),
('Kirsten', 'Dunst'),
('Mahershala', 'Ali'),
('Glen', 'Powell'),
('Ariana', 'Neal'), 
('Russell', 'Crowe'),
('Jennifer', 'Connelly'),
('Paul', 'Bettany'),
('Christopher', 'Plummer'),
('Adam', 'Goldberg'),
('Anthony', 'Rapp'),
('Judd', 'Hirsch'),
('Jennifer', 'Lawrence'),
('Michael', 'Sheen'),
('Laurence', 'Fishburne'),
('Andy', 'García'),
('Aurora', 'Perrineau'),
('Kristin', 'Brock'),
('Julee', 'Cerda'),
('Fred', 'Melamed'),
('Anne', 'Hathaway'),
('Andre', 'Braugher'),
('Dianne', 'Wiest'),
('David', 'Morse'),
('William', 'B. Davis'),
('Ryan', 'Robbins'),
('Clea', 'DuVall'),
('Don', 'Thompson'),
('Bryan', 'Cranston'),
('Alan', 'Arkin'),
('John', 'Goodman'),
('Victor', 'Garber'),
('Tate', 'Donovan'),
('Rory', 'Cochrane'),
('Noomi', 'Rapace'),
('Michael', 'Fassbender'),
('Charlize', 'Theron'),
('Logan', 'Marshall-Green'),
('Guy', 'Pearce'),
('Idris', 'Elba'),
('Sean', 'Harris'),
('Rafe', 'Spall'),
('Kate', 'Dickie'),
('Emut', 'Elliott'),
('Benedict', 'Wong'),
('Lucy', 'Hutchinson'),
('Patrick', 'Wilson'),
('Ian', 'Whyte'),
('Branwell', 'Donaghey'),
('Vladimir', 'Furdik'),
('C.C.', 'Smiff'),
('Shane', 'Steyn'),
('John', 'Lebar'),
('Jake', 'Gyllenhaal'),
('Rebecca', 'Ferguson'),
('Ryan', 'Reynolds'),
('Hiroyuki', 'Sanada'),
('Airyon', 'Bakare'),
('Olga', 'Dihovichnaya'),
('Naoko', 'Mori'),
('Haruka', 'Kuroda'),
('Camiel', 'Warren-Taylor'),
('Rosamund', 'Pike'),
('Sam', 'Riley'),
('Aneurin', 'Barnard'),
('Simon', 'Russell Beale'),
('Jonathan', 'Aris'),
('Tim', 'Woodward'),
('Katherine', 'Parkinson'),
('Chris', 'O\'Dowd'),
('Gragam', 'Linehan'),
('Richard', 'Ayoade'),
('Matt', 'Berry'),
('Tom', 'Binns'),
('Lewis', 'Macleod'),
('Noel', 'Fielding'),
('Peter', 'Serafinowicz'),
('Tuppence', 'Middleton'),
('Ian', 'Bonar'),
('Elisabeth', 'Hopper'),
('Nick', 'Bartlett'),
('Wunmi', 'Mosaku'),
('Alex', 'Lawther'),
('Jerome', 'Flynn'),
('Susannah', 'Doyle'),
('Madeline', 'Brewer'),
('Ariane', 'Labed'),
('Sarah', 'Snook'),
('Michael', 'Kelly'),
('Jola', 'Bokinni'),
('Faye', 'Marsay'),
('Ben', 'Wong'),
('Jonas', 'Karlsson'),
('Indira', 'Ainger'),
('James', 'Lance'),
('David', 'Ajala'),
('Sarah', 'Abbott'),
('Clint', 'Dyer'),
('Jake', 'Davies'),
('Letitia', 'Wright'),
('Babs', 'Olusanmokun'),
('Georgina', 'Campbell'),
('Jesse', 'Plemons'),
('Aldis', 'Hodge'),
('Kiran', 'Sonia Sawar'),
('Miley', 'Cyrus'),
('Anthony', 'Mackie'),
('Nicole', 'Beharie'),
('Gugu', 'Mbatha-Raw'),
('Tom', 'Cruise'), 
('Jon', 'Voight'), 
('Emmanuelle', 'Béart'), 
('Henry', 'Czerny'), 
('Jean', 'Reno'), 
('Ving', 'Rhames'), 
('Kristin', 'Scott Thomas'), 
('Vanessa', 'Redgrave'), 
('Ingeborga', 'Dapkünaitè'),
('Elizabeth', 'Debicki'),
('Luca', 'Calvani'),
('Sylvester', 'Groth'),
('Misha', 'Kuznetsov'),
('Hugh', 'Grant'),
('Christian', 'Berkel'),
('Dwayne', 'Johnson'),
('Kevin', 'Hart'),
('Jack', 'Black'),
('Karen', 'Gillan'),
('Nick', 'Jonas'),
('Rhys', 'Darby'),
('Bobby', 'Cannavale'),
('Alex', 'Wolff'),
('Ser\'Darius', 'Blain'),
('Colin', 'Hanks'),
('Madison', 'Iseman'),
('Morgan', 'Turner'),
('Sean', 'Buxton'),
('Mason', 'Guccione'),
('Guy', 'Williams'),
('Marianna', 'Di Martino'), 
('Matthew', 'Goode'),
('Rory', 'Kinnear'),
('Allen', 'Leech'),
('Matthew', 'Beard'),
('Charles', 'Dance'),
('Mark', 'Strong'),
('James', 'Northcote'),
('Gemma', 'Chan'),
('Emily', 'Berrington'),
('Lucy', 'Carless'),
('Colin', 'Morgan'),
('Theo', 'Stevenson'),
('Pixie', 'Daves'),
('Tom', 'Goodman-Hill'),
('Ivanno', 'Jeremiah'),
('Ruth', 'Bradley'),
('Will', 'Tudor'),
('Neil', 'Maskell'),
('Billy', 'Jenkins'),
('Bella', 'Dayne'),
('Thusitha', 'Jayasumdera'),
('Danny', 'Webb'),
('Carrie-Anne', 'Moss'),
('Dominic', 'Cooper'),
('Imogen', 'Poots'),
('Ramón', 'Rodríguez'),
('Michael', 'Keaton'),
('Rami', 'Malek'),
('Kid', 'Cudi'),
('Dakota', 'Johnson'),
('Harrison', 'Gilbertson'),
('Carmela', 'Zumbado'),
('Jalil', 'Jay Lynch'),
('Nick', 'Chinlund'),
('Chad', 'Randall'),
('Julianne', 'Nicholson'),
('Jean', 'Smart'),
('Angourie', 'Rice'),
('Evan', 'Peters'),
('Sosie', 'Bacon'),
('David', 'Denman'),
('Neal', 'Huff'),
('James', 'McArdle'),
('John', 'Douglas Thompson'),
('Joe', 'Tippett'),
('Cameron', 'Mann'),
('Chinasa', 'Ogbuagu'),
('Jamie', 'Foxx'),
('Kerry', 'Washington'),
('Regina', 'King'),
('Harry', 'Lennix'),
('Clifton', 'Powell'),
('Bokeem', 'Woodbine'),
('Sharon', 'Warren'),
('C.J.', 'Sanders'),
('Curtis', 'Armstrong'),
('Michaela', 'Coel'),
('Daniel', 'Lapaine'),
('Hannah', 'John-Kamen'),
('Andrew', 'Roux'),
('Claire', 'Keelan'),
('Sinéad', 'Matthews'),
('Anna', 'Wilson-Jones'),
('Paul', 'Popplewell'),
('Julia', 'Davis'),
('Ashley', 'Thomas'),
('Kerrie', 'Hayes'),
('Amy', 'Beth Hayes'),
('Rebekah', 'Staton'),
('Rhashan', 'Stone'),
('Phoebe', 'Fox'),
('Jimi', 'Mistry'),
('Cherry', 'Jones'),
('Alice', 'Eve'),
('Susannah', 'Fielding'),
('Demetri', 'Goritsas'),
('Kadiff', 'Kirwan'),
('Sope', 'Dirisu'),
('Jackson', 'Bews'),
('Annabel', 'Davis'),
('Billy', 'Griffin Jr.'),
('Paul', 'Lawrence Kitson'),
('Jeff', 'Mash'),
('Patrick', 'Kennedy'),
('Lydia', 'Wilson'),
('Alastair', 'Mackenzie'),
('Chetna', 'Pandya'),
('Nora', 'Lum'),
('Danny','DeVito'),
('Eugene', 'O\'Hare'),
('Danny', 'Glover'),
('Simona', 'Brown'),
('Eve', 'Hewson'),
('Toma', 'Bateman'),
('Robert', 'Aramayo'),
('Tyler', 'Howitt'),
('Georgie', 'Glen'),
('Kamontip', 'Krissy Ashton'),
('Rob', 'Horrocks'),
('Joakim', 'Skarli'),
('Olivia', 'Wilde'),
('Matt', 'Letscher'),
('Portia', 'Doubleday'),
('Spike', 'Jonze'),
('Gal', 'Gadot'),
('Chris', 'Pine'),
('Robin', 'Wright'),
('Lilly', 'Aspell'),
('Amr', 'Waked'),
('Kristoffer', 'Polaha'),
('Jeffrey', 'Tambor'),
('Cynthia', 'Addai-Robinson'),
('John', 'Lithgow'),
('Andy', 'Umberger'),
('Alison', 'Wright'),
('Daeg', 'Faerch'),
('Seth', 'Lee'),
('Tait', 'Fletcher'),
('Angel', 'Giuffria'),
('Ron', 'Yuan'),
('Scott', 'Hunter'),
('Dennis', 'Keiffer'),
('Jake', 'Presley'),
('Hugh', 'Jackman'),
('Allison', 'Janney'),
('Geraldine', 'Viswanathan'),
('Rafael', 'Casal'),
('Stephen', 'Spinella'),
('Annaleigh', 'Ashford'),
('Ray', 'Romano'),
('Hari', 'Dhillon'),
('Jerremy', 'Shamos'),
('Stephanie', 'Kurtzuba'),
('Catherine', 'Curtin'),
('Kathrine', 'Narducci'),
('Ray', 'Abruzzo'),
('Ben', 'Stiller'),
('Robin', 'Williams'),
('Carla', 'Gugino'),
('Dick', 'Van Dyke'),
('Steve', 'Coogan'),
('Jake', 'Cherry'),
('Mickey', 'Rooney'),
('Bill', 'Cobbs'),
('Owen', 'Wilson'),
('Ricky', 'Gervais'),
('Kim', 'Raver'),
('Mizuo', 'Peck'),
('Gwilym', 'Lee'),
('Ben', 'Hardy'),
('Joseph', 'Mazzello'),
('Lucy', 'Boynton'),
('Aidan', 'Gillen'),
('Tom', 'Hollander'),
('Mike', 'Myers'),
('Julianne', 'Hough'),
('Diego', 'Boneta'),
('Alec', 'Baldwin'),
('Russell', 'Brand'),
('Malin', 'Åkerman'),
('Paul', 'Giamatti'),
('Catherine', 'Zeta-Jones'),
('Mary', 'J. Blige'),
('Erica', 'Frene'),
('Shane', 'Hartline'),
('James', 'Martin Kelly'),
('Will', 'Forte'),
('Eli', 'Roth'),
('Joel', 'Courtney'),
('Elle', 'Fanning'),
('Riley', 'Griffiths'),
('Noah', 'Emmerich'),
('AJ', 'Michalka'),
('Ryan', 'Lee'),
('Ron', 'Eldard'),
('Gabriel', 'Basso'),
('Justice', 'Smith'),
('Daniella', 'Pineda'),
('James', 'Cromwell'),
('Ted', 'Levine'),
('Jeff', 'Goldblum'),
('BD', 'Wong'),
('Geraldine', 'Chaplin'),
('Isabella', 'Sermon'),
('Kevin', 'Layne'),
('Harrison', 'Ford'),
('Shia', 'LaBeouf'),
('Cate', 'Blanchett'),
('Karen', 'Allen'),
('John', 'Hurt'),
('Jim', 'Broadbent'),
('Igor', 'Jijikine'),
('Dimitri', 'Diatchenko'),
('Sean', 'Astin'),
('Josh', 'Brolin'),
('Jeff', 'Cohen'),
('Corey', 'Feldman'),
('Kerri', 'Green'),
('Martha', 'Plimpton'),
('Jonathan', 'Ke Quan'),
('John', 'Matuszak'),
('Robert', 'Davi'),
('Bonnie', 'Hunt'),
('Paul', 'Newman'),
('Larry', 'the Cable Guy'),
('Tony', 'Shalhoub'),
('Cheech', 'Marin'),
('Michael', 'Wallis'),
('George', 'Carlin'),
('Paul', 'Dooley'),
('Chris', 'Miller'),
('Tom', 'McGrath'),
('Danny', 'Jacobs'),
('Andy', 'Richter'),
('Nicole', 'Sullivan'),
('Christopher', 'Knights'),
('Wayne', 'Knight'),
('Dale', 'Midkiff'),
('Fred', 'Gwynne'),
('Denise', 'Crosby'),
('Brad', 'Greenquist'),
('Michael', 'Lombard'),
('Miko', 'Hughes'),
('Blaze', 'Berdahl'),
('Susan', 'Blommaert'),
('Mara', 'Clark'),
('Craig T.', 'Nelson'),
('JoBeth', 'Williams'),
('Beatrice', 'Straight'),
('Dominique', 'Dunne'),
('Oliver', 'Robins'),
('Heather', 'O\'Rourke'),
('Michael', 'McManus'),
('Virginia', 'Kiser'),
('Martin', 'Casella'),
('Audrey', 'Tautou'),
('Ian', 'McKellen'),
('Alfred', 'Molina'),
('Jürgen', 'Prochnow'),
('Jean-Yves', 'Berteloot'),
('Etienne', 'Chicot'),
('Rowan', 'Atkinson'),
('Natalie', 'Imbruglia'),
('Ben', 'Miller'),
('Greg', 'Wise'),
('Tasha', 'de Vasconcelos'),
('Douglas', 'McFerran'),
('Steve', 'Nicolson'),
('Terence', 'Harvey'),
('Billy', 'Crudup'),
('Frances', 'McDormand'),
('Kate', 'Hudson'),
('Jason', 'Lee'),
('Zoey', 'Deschanel'),
('Michael', 'Angarano'),
('Anna', 'Paquin'),
('Fairuzza', 'Balk'),
('Joan', 'Cusack'),
('Mike', 'White'),
('Sarah', 'Silverman'),
('Lee', 'Wilkof'),
('Kate', 'McGregor-Stewart'),
('Adam', 'Pascal'),
('Suzzane', 'Douglas'),
('Macaulay', 'Culkin'),
('Joe', 'Pesci'),
('Daniel', 'Stern'),
('John', 'Heard'),
('Catherine', 'O\'Hara'),
('Roberts', 'Blossom'),
('Devin', 'Ratray'),
('Michael C.', 'Maronna'),
('Hillary', 'Wolf'),
('Vince', 'Vaughn'),
('Will', 'Ferrell'),
('Rose', 'Byrne'),
('Aasif', 'Mandvi'),
('Josh', 'Brener'),
('Dylan', 'O\'Brien'),
('Tiya', 'Sircar'),
('Tobit', 'Raphael'),
('Josh', 'Gad'),
('Jessica', 'Szohr'),
('Rob', 'Riggle'),
('Eric', 'André'),
('Harvey', 'Guillén'),
('Gary', 'Anthony Williams'),
('Bruno', 'Amato'),
('Karen', 'Ceesay'),
('Rebecca', 'Hazlewood'),
('Sacha', 'Dhawan'),
('Diedrich', 'Bader'),
('Pippa', 'Black'),
('Parvesh', 'Ceena'),
('Thushari', 'Jayasekera'),
('Ben', 'Rappaport'),
('Guru', 'Singh'),
('Rizwan', 'Manji'),
('Anisha', 'Nagarajan'),
('Carla', 'Gallo'),
('Radhika', 'Chaudhari'),
('Nicholas', 'Logan'),
('Blake', 'Lively'),
('Óscar', 'Jaenada'),
('Janelle', 'Bailley'),
('Chelsea', 'Moody'),
('Angelo Josue', 'Lozano Corzo'),
('José Manuel', 'Trujillo Salas'),
('Sedona', 'Legge'),
('Pablo', 'Calva'),
('Jogn', 'Hawkes'),
('Sam', 'Worthington'),
('Martin', 'Henderson'),
('Thomas M.', 'Wright'),
('Clive', 'Standen'),
('Mia', 'Goth'),
('Raúl', 'Juliá'),
('Anjelica', 'Huston'),
('Christopher', 'Lloyd'),
('Christina', 'Ricci'),
('Carel', 'Struycken'),
('Dan', 'Hedaya'),
('Jimmy', 'Workman'),
('Elizabeth', 'Wilson'),
('Dana', 'Ivey');

-- Insertar series en la tabla "contenido": idCategoria = 1.
INSERT INTO contenido (titulo, resumen, temporadas, duracion, trailer, idCategoria) VALUES 
('The Mandalorian', 'Ambientada tras la caída del Imperio y antes de la aparición de la Primera Orden, la Serie sigue los pasos de un pistolero solitario en las aventuras que protagoniza en los confines de la galaxia, donde no alcanza la autoridad de la Nueva República.', 2, NULL, 'https://www.youtube.com/embed/aOC8E8z_ifw', 1), 
('The Umbrella Academy', 'La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.', 1, NULL, 'https://www.youtube.com/embed/KHucKOK-Vik', 1),
('Gambito de Dama', 'En los cincuenta, una joven de un orfanato descubre que tiene un increíble don para el ajedrez y recorre el arduo camino a la fama mientras lucha contra las adicciones.', 1, NULL, 'https://www.youtube.com/embed/lbleRbyGKL4', 1),
('Riverdale', 'El paso a la edad adulta incluye sexo, romance, escuela y familia. Para Archie y sus amigos, también hay misterios oscuros.', 5, NULL, 'https://www.youtube.com/embed/HxtLlByaYTc', 1),
('The Crown', 'Este drama narra las rivalidades políticas y el romance de la reina Isabel II, así como los sucesos que moldearon la segunda mitad del siglo XX.', 4, NULL, 'https://www.youtube.com/embed/JWtnJjn6ng0', 1),
('Juego de tronos', 'En un mundo fantástico y en un contexto medieval varias familias, relativas a la nobleza, se disputan el poder para dominar el territorio ficticio de Poniente (Westeros) y tomar el control de los Siete Reinos desde el Trono de Hierro, lugar donde el rey ejerce el poder.', 8, NULL, 'https://www.youtube.com/embed/KPLWWIOCOOQ', 1),
('The Flash', 'Sigue las veloces aventuras de Barry Allen, un joven común y corriente con el deseo latente de ayudar a los demás. Cuando una inesperada partícula aceleradora golpea por accidente a Barry, de pronto se encuentra cargado de un increíble poder para moverse a increíbles velocidades. Mientras Barry siempre ha tenido el alma de un héroe, sus nuevos poderes le han dado la capacidad de actuar como tal.', 6, NULL, 'https://www.youtube.com/embed/Yj0l7iGKh8g', 1),
('The Big Bang Theory', 'Leonard y Sheldon son dos físicos que comparten trabajo y apartamento. La Serie comienza con la mudanza de Penny, su nueva y atractiva vecina, y hace hincapié en la dificultad de los físicos para relacionarse con personas fuera de su entorno para dar lugar a situaciones cómicas.', 12, NULL, 'https://www.youtube.com/embed/WBb3fojgW0Q', 1),
('Friends', 'Friends narra las aventuras y desventuras de seis jóvenes de Nueva York: Rachel, Monica, Phoebe, Ross, Chandler y Joey. Ellos forman una unida pandilla de amigos que viven en Manhattan y que suelen reunirse en sus apartamentos o en su bar habitual cafetería, el Central Perk. A pesar de los numerosos cambios que se producen en sus vidas, su amistad es inquebrantable en la dura batalla por salir adelante en sus periplos profesionales y personales.', 10, NULL, 'https://www.youtube.com/embed/ekYGfU0XIx0', 1),
('Anne with an E', 'Anne Shirley es una niña huérfana que vive en un pequeño pueblo llamado Avonlea que pertenece a la Isla del Príncipe Eduardo, en el año 1890. Después de una infancia difícil, donde fue pasando de orfanato a hogares de acogida, es enviada por error a vivir con una solterona y su hermano. Cuando cumple 13 años, Anne va a conseguir transformar su vida y el pequeño pueblo donde vive gracias a su fuerte personalidad, intelecto e imaginación. Basada en la inolvidable novela.', 2, NULL, 'https://www.youtube.com/embed/M4T-_aB8smU', 1),
('Expedientes Secretos X', 'Fox Mulder y Dana Scully son dos investigadores del FBI que investigan casos sin resolución ni explicación, ya sea por razones paranormales (espíritus, criaturas extrañas, aliens...) ya porque el gobierno se ha encargado de ocultar todo tipo de pruebas. Cuando Mulder tenía doce años, su hermana pequeña fue secuestrada por unos desconocidos, aunque él cree que, en realidad, fue abducida por extraterrestres. Tras acabar sus estudios en la universidad de Oxford, ingresó en la Academia de Quantico, donde se ganó el apodo de 'siniestro'', 11, NULL, 'https://www.youtube.com/embed/KKziOmsJxzE', 1),
('Chernobyl', 'Sigue «la verdadera historia de una de las peores catástrofes provocadas por el hombre y habla de los valientes hombres y mujeres que se sacrificaron para salvar a Europa de un desastre inimaginable. La miniSerie se centra en el desgarrador alcance del desastre de la planta nuclear que ocurrió en Ucrania en abril de 1986, revelando cómo y por qué ocurrió, además contando las sorprendentes y notables historias de los héroes que lucharon y cayeron.', 1, NULL, 'https://www.youtube.com/embed/s9APLXM9Ei8', 1),
('Westworld', 'Westworld es una oscura odisea acerca del amanecer de la conciencia artificial y la evolución del pecado. Situada en la intersección del futuro cercano y el pasado reimaginado, explora un mundo donde cada apetito humano, sin importar cuán noble o depravado, puede ser saciado. Está ambientada en un parque temático futurista dirigido por el Dr. Robert Ford (Anthony Hopkins). Las instalaciones cuentan con androides caracterizados del western americano, y gracias a ellos los visitantes pueden introducirse en cualquier tipo de fantasía por muy oscura que sea.', 3, NULL, 'https://www.youtube.com/embed/qLFBcdd6Qw0', 1),
('Halt and Catch Fire', 'Situada en los inicios de la década de 1980, un visionario ficticio, un ingeniero electrónico y una prodigiosa ingeniera, se alían a una programadora de software para confrontar con las corporaciones informáticas dominantes de la época. El Personal de la firma y sus socios de negocio, comenzarán una carrera que cambiará la cultura en el Estado de Texas, cuna de las empresas de tecnología, casi de la misma forma que lo es hoy Silicon Valey. \n Esta historia ficticia emula el trabajo realizado, en su momento, por la firma Compaq, cuando clonó el BIOS de las Computadoras Personales IBM, dando vida así al económico mercado de los clones. Mostrando también, a lo largo de sus 4 temporadas, el nacimiento de la arquitectura abierta de hardware, los videojuegos online, las salas de chat y de trueque de productos físicos, los BBS, y las primeras nubes computacionales, hasta la llegada de Internet (sin dejar afuera la guerra de los web browsers).', 4, NULL, 'https://www.youtube.com/embed/pWrioRji60A', 1),
('Two and a half men', 'Un quiropráctico y padre soltero, Alan Harper, vive en una casa al frente de la playa con su hijo mediocre, Jake, y un billonario de la Internet divorciado Walden Schmidt, que se muda con la familia de los Harper y ofrece comprar la casa luego de la muerte inesperada del hermano de Alan, Charlie, que era el propietario de la casa en la que vivía con Alan y Jake, luego de que padre e hijo se mudaran después del divorcio de Alan. La exesposa de Alan y madre de Jake, Judith, permanece en sus vidas.', 12, NULL, 'https://www.youtube.com/embed/mVHDanSl2pc', 1),
('La casa de Papel', 'Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.', 4, NULL, 'https://www.youtube.com/embed/w1jkStuRQU8', 1),
('Stranger Things', 'Pasan cosas muy extrañas en Hawkins, Indiana, tras una desaparición que revela la presencia de una niña con poderes sobrenaturales. Después de la extraña desaparición de un niño, un pueblo se encuentra ante un misterio que revela experimentos secretos, fuerzas sobrenaturales.', 4, NULL, 'https://www.youtube.com/embed/b9EkMc79ZSU', 1),
('The Office', 'Steve Carell protagoniza The Office, un fresco y divertido vistazo, con formato pseudo-documental, al día a día en la vida de unos excéntricos trabajadores de la empresa Dunder Mifflin. El serio pero despistadísimo director Michael Scott se considera un magnífico jefe y mentor, pero realmente inspira más críticas que respeto a sus empleados.', 9, NULL, 'https://www.youtube.com/embed/LHOtME2DL4g', 1),
('The Good Doctor', 'Un cirujano joven y autista que padece el síndrome del sabio empieza a trabajar en un hospital prestigioso. Allá tendrá que vencer el escepticismo con el que sus colegas lo reciben.', 4, NULL, 'https://www.youtube.com/embed/fYlZDTru55g', 1),
('The IT Crowd', 'En un desordenado sótano en las entrañas de Industrias Reynholm habitan Roy y Moss, los componentes del Departamento de informática. Víctimas del desprecio y del escarnio de sus compañeros más guays, su mundo de servidores y cortafuegos se ve interrumpido por la llegada de Jen, su nueva jefa, que sabe tanto de ordenadores como un yak.', 4, NULL, 'https://www.youtube.com/embed/wCa1jfo93jQ', 1),
('Humans', 'En un presente paralelo donde el último gadget que hay que tener para cualquier familia ocupada es un 'Synth' - un sirviente robótico altamente desarrollado que es tan similar a un humano real que está transformando la manera en que vivimos.', 3, NULL, 'https://www.youtube.com/embed/BV8qFeZxZPE', 1),
('Mare of Easttown', 'Mare of Easttown es una miniserie estadounidense de drama y misterio creada por Brad Ingelsby cuenta la historia de Mare Sheehan, una detective de un pequeño pueblo de Pensilvania que investiga un asesinato local mientras trata de evitar que su vida se desmorone a raiz de la muerte de su hijo, su separación, y la posible restitución de su nieto a su madre biológica.', 1, NULL, 'https://www.youtube.com/embed/miQqyfO66uw', 1),
('Black Mirror', 'Black Mirror es una serie de televisión británica creada por Charlie Brooker que muestra el lado oscuro de la vida y la tecnología. La serie es producida por Zeppotron para Endemol. En cuanto al contenido del programa y la estructura, Brooker ha señalado que 'cada episodio tiene un tono diferente, un entorno diferente, incluso una realidad diferente, pero todos son acerca de la forma en que vivimos ahora - y la forma en que podríamos estar viviendo en 10 minutos si somos torpes'.', 5, NULL, 'https://www.youtube.com/embed/jVHCQfcugdw', 1),
('Detrás de sus ojos', 'Una madre soltera se adentra en un mundo de retorcidos juegos psicológicos cuando inicia una relación cuasi-no consentida con su jefe, un psiquiatra, y se hace amiga en secreto de su misteriosa esposa. La trama se bassa en un thriller sobre un triángulo amoroso perverso, más la introducción sutilmente de un elemento clave, que dará un giro notable a la obra.', 1, NULL, 'https://www.youtube.com/embed/c4LtoWQaLxk', 1),
('Outsourced', 'Ambientada en el continente estadounidense, una empresa norteamericana que busca reducir los gastos, asciende a su mejor empleado del Call Center, poniéndolo a cargo del mismo. La única condición para dicho empleado, es viajar a la India, lugar en el mundo donde tercerizan el servicio ode atención al cliente, para abaratar costos. Allí, en la Ciudad de Bombay, los nativos le explican la cultura indú a los nóveles norteamericanos, y viceversa. Tendrán que convivir cada uno de los empleados de estos diferentes países, con sus pares y/o jefes opuestos en cultura.', 1, NULL, 'https://www.youtube.com/embed/_wR3LhFlgGo', 1);

-- Insertar peliculas en la tabla "contenido": idCategoria = 2. 
INSERT INTO contenido (titulo, resumen, temporadas, duracion, trailer, idCategoria) VALUES 
('Enola Holmes', 'La hermana menor de Sherlock, descubre que su madre ha desaparecido y se dispone a encontrarla. En su búsqueda, saca a relucir el sabueso que corre por sus venas y se encuentra con una conspiración que gira en torno a un misterioso lord, demostrando que su ilustre hermano no es el único talento en la familia.', NULL, '97 minutos', 'https://www.youtube.com/embed/3t1g2pa355k', 2),
('Guasón', 'Arthur Fleck (Phoenix) es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una Serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en el popular personaje de DC Comics Joker, conocido como archivillano de Batman, pero que en este film tomará un cariz más realista y oscuro.', NULL, '97 minutos', 'https://www.youtube.com/embed/zAGVQLHvwOY', 2),
('Avengers: End Game', 'Después de los devastadores eventos de los Vengadores: Infinity War (2018), el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el equilibrio del universo.', NULL, '97 minutos', 'https://www.youtube.com/embed/TcMBFSGVi1c', 2),
('Ava', 'Ava es una mortífera asesina a sueldo que trabaja para una organización de operaciones encubiertas, que viaja por todo el mundo acabando con aquellos objetivos que nadie más puede derribar. Cuando uno de sus encargos sale mal, Ava tendrá que luchar por una vida.', NULL, '97 minutos', 'https://www.youtube.com/embed/eLEwNo78f0k', 2),
('Aves de presa (Harley Quinn)', 'Después de separarse de Joker, Harley Quinn y otras tres heroínas (Canario Negro, Cazadora y Renée Montoya) unen sus fuerzas para salvar a una niña (Cassandra Cain) del malvado rey del crimen Máscara Negra.', NULL, '97 minutos', 'https://www.youtube.com/embed/saUmnenKbBM', 2),
('Archivo', '2038: George Almore está trabajando en una verdadera IA equivalente a la humana. Su último prototipo está casi listo. Esta fase sensible también es la más arriesgada. Especialmente porque tiene un objetivo que debe ocultarse a toda costa: reunirse con su esposa muerta.', NULL, '97 minutos', 'https://www.youtube.com/embed/VHSoCnDioAo', 2),
('3022', 'La película está ambientada en una estación espacial en el futuro. La tripulación sufre un estrés traumático y considera abandonar su misión después de observar lo que creen que es la destrucción de la Tierra. La película se muestra como una Serie de flashbacks y flash-forward.', NULL, '97 minutos', 'https://www.youtube.com/embed/AGQ7OkmIx4Q"', 2),
('IT - Capítulo 2', 'En este segundo capitulo Han pasado 27 años desde que el 'Club de los Perdedores', formado por Bill, Berverly, Richie, Ben, Eddie, Mike y Stanley, se enfrentaran al macabro y despiadado Pennywise (Bill Skarsgård). En cuanto tuvieron oportunidad, abandonaron el pueblo de Derry, en el estado de Maine, que tantos problemas les había ocasionado. Sin embargo, ahora, siendo adultos, parece que no pueden escapar de su pasado. Todos deberán enfrentarse de nuevo al temible payaso para descubrir si de verdad están preparados para superar sus traumas de la infancia.', NULL, '97 minutos', 'https://www.youtube.com/embed/hZeFeYSmBcg', 2),
('Pantera Negra', 'T’Challa (Chadwick Boseman) regresa a su hogar en la apartada nación africana de Wakanda para servir como líder de su país. Tras suceder a su padre en el trono, pasa a convertirse en Pantera Negra, una sigilosa criatura de la noche, con agudos sentidos felinos y otras habilidades como súper fuerza e inteligencia, agilidad, estrategia o maestro del combate sin armas. Es bajo el liderazgo de T’Challa como Wakanda consigue convertirse en una de las naciones más ricas y tecnológicamente avanzadas del planeta.', NULL, '97 minutos', 'https://www.youtube.com/embed/BE6inv8Xh4A', 2),
('Contra lo imposible (Ford versus Ferrari)', 'Los ganadores del Premio de la Academia® Matt Damon y Christian Bale protagonizan CONTRA LO IMPOSIBLE, basada en la historia real del visionario diseñador americano de automóviles Carroll Shelby (Damon) y el intrépido piloto británico Ken Miles (Bale). Juntos construyen un nuevo coche de carreras para Ford Motor Company y así enfrentar a Enzo Ferrari en las 24 Horas de Le Mans en Francia en 1966.', NULL, '97 minutos', 'https://www.youtube.com/embed/SOVb0-2g1Q0', 2),
('Centígrados', 'Una joven pareja estadounidense viaja a las montañas árticas de Noruega. Después de detenerse durante una tormenta de nieve, se despiertan atrapados en su SUV, enterrados bajo capas de nieve y hielo.', NULL, '97 minutos', 'https://www.youtube.com/embed/0RvV7TNUlkQ', 2),
('DOOM: Aniquilación', 'Doom: Aniquilación sigue a un grupo de marines espaciales que han respondido a una llamada de alerta de una base en la luna marciana, solo para descubrir que ha sido tomada por criaturas demoníacas que amenazan con desatar el infierno en la tierra.', NULL, '97 minutos', 'https://www.youtube.com/embed/nat3u3gAVLE', 2),
('Contagio', 'De repente, sin saber cuál es su origen, aunque todo hace sospechar que comienza con el viaje de una norteamericana a un casino de Hong Kong, un virus mortal comienza a propagarse por todo el mundo. En pocos días, la enfermedad empieza a diezmar a la población. El contagio se produce por mero contacto entre los seres humanos. Un thriller realista y sin efectos especiales sobre los efectos de una epidemia.', NULL, '97 minutos', 'https://www.youtube.com/embed/4sYSyuuLk5g', 2),
('Viuda Negra', 'Primera pelicula individual de la Viuda Negra en el universo cinematografico de Marvel, contando su historia desde que se inició como doble agente rusa, su niñez, sus misiones, y su actualidad, después de Avengers.', NULL, '97 minutos', 'https://www.youtube.com/embed/BIn8iANwEog', 2),
('The Martian', 'Durante una misión a Marte de la nave tripulada Ares III, una fuerte tormenta se desata dando por desaparecido y muerto al astronauta Mark Watney (Matt Damon), sus compañeros toman la decisión de irse pero él ha sobrevivido. Está solo y sin apenas recursos en el planeta. Con muy pocos medios deberá recurrir a sus conocimientos, su sentido del humor y un gran instinto de supervivencia para lograr sobrevivir y comunicar a la Tierra que todavía está vivo esperando que acudan en su rescate.', NULL, '97 minutos', 'https://www.youtube.com/embed/XvB58bCVfng', 2),
('Ex-Machina', 'Un programador multimillonario selecciona a Caleb, un joven empleado de su empresa, para que pase una semana en un lugar remoto con el objetivo de que participe en un test en el que estará involucrada su última creación: un robot-mujer en el que inteligencia artificial lo es todo.', NULL, '97 minutos', 'https://www.youtube.com/embed/XRYL5spvEcI', 2),
('Jurassic World', 'Veintidós años después de lo ocurrido en Jurassic Park, la isla Nublar ha sido transformada en un enorme parque temático, Jurassic Wold, con versiones «domesticadas» de algunos de los dinosaurios más conocidos. Cuando todo parece ir sobre ruedas y ser el negocio del siglo, un nuevo dinosaurio de especie desconocida, pues ha sido creado manipulando genéticamente su ADN, y que resulta ser mucho más inteligente de lo que se pensaba, se escapa de su recinto y comienza a causar estragos entre los visitantes del Parque.', NULL, '97 minutos', 'https://www.youtube.com/embed/RFinNxS5KN4', 2),
('Soy leyenda', 'Años después de que una plaga mate a la mayoría de la humanidad y transforme al resto en monstruos, el único superviviente en la ciudad de Nueva York lucha valientemente para encontrar una cura.', NULL, '97 minutos', 'https://www.youtube.com/embed/dtKMEAXyPkg', 2),
('El primer hombre en la luna', 'Cuenta la historia de la misión de la NASA que llevó al primer hombre a la luna, centrada en Neil Armstrong (interpretado por Ryan Gosling) y el periodo comprendido entre los años 1961 y 1969. Un relato en primera persona, basado en la novela de James R. Hansen, que explora el sacrificio y el precio que representó, tanto para Armstrong como para Estados Unidos, una de las misiones más peligrosas de la historia.', NULL, '97 minutos', 'https://www.youtube.com/embed/PSoRx87OO6k', 2),
('Titanes del pacífico - La insurrección', 'Han pasado 10 años tras la primera invasión que sufrió la humanidad, pero la lucha aún no ha terminado. El planeta vuelve a ser asediado por los Kaiju, una raza de alienígenas colosales, que emergen desde un portal interdimensional con el objetivo de destruir a la raza humana. Ante esta nueva amenaza, los Jaegers, robots gigantes de guerra pilotados por dos personas para sobrellevar la inmensa carga neuronal que conlleva manipularlos, ya no están a la altura de lo que se les viene encima. Será entonces cuando los supervivientes de la primera invasión, además de nuevos personajes como el hijo de Pentecost, tendrán que idear la manera de sorprender al enorme enemigo, apostando por nuevas estrategias defensivas y de ataque. Con la Tierra en ruinas e intentando reconstruirse, esta nueva batalla puede ser decisiva para el futuro.', NULL, '97 minutos', 'https://www.youtube.com/embed/_EhiLLOhVis', 2),
('JOBS: La Vida De Steve Jobs', 'Sólo hace falta una persona para empezar una revolución. Jobs es la extraordinaria historia de Steve Jobs, el original innovador y emprendedor que no dejó que nada se interpusiera en su camino hacia la grandeza. La película cuenta la épica y turbulenta historia de Jobs mientras abría un camino que cambió la tecnología - y el mundo - para siempre. Su vida es repasada desde que era adolescente, intentando estudiar en la universidad, hasta el año 2001, cuando el iPod fue presentado al mundo y comenzó a 'allanar' el camino para lo que años después, sería el iPhone.', NULL, '104 minutos', 'https://www.youtube.com/embed/FrvkCS0ZGPU', 2),
('Piratas de Silicon Valey', 'Esta película es el documental semigracioso sobre los hombres que hicieron el mundo de la tecnología lo que es hoy, sus luchas durante el colegio, la fundación de sus compañías y las acciones ingeniosas que tomaron para aumentar los Imperios corporativos globales de Apple Computer Inc. y Microsoft Corporation.', NULL, '104 minutos', 'https://www.youtube.com/embed/lEyrivrjAuU', 2),
('Red Social', 'En una noche de otoño de 2003, el genio de la programación de computación de la Universidad de Harvard Mark Zuckerberg se sienta en su computadora y acaloradamente comienza a trabajar en una nueva idea. En una furia de los blogs y la programación, lo que comienza en su dormitorio como un pequeño sitio entre amigos pronto se convierte en una red social global y una revolución en la comunicación. A sólo seis años y 500 millones de amigos más tarde, Mark Zuckerberg es el multimillonario más joven de la historia ... pero para este empresario, el éxito conduce a complicaciones tanto personales como legales.', NULL, '116 minutos', 'https://www.youtube.com/embed/lB95KLmpLR4', 2),
('Antitrust', 'Milo Hoffman es un joven informático increíblemente prometedor para su edad que rápidamente es contratado por una importante empresa de Sillicon Valley. El empleo de sus sueños se ha hecho realidad, ya que ahí puede trabajar con los ordenadores más potentes del mundo y con las últimas tecnologías que aún no han salido al mercado. El Paraíso de un informático. Su jefe, Gary Winston , es un poderoso pez gordo de la industria que en un principio parece un tipo íntegro y legal. Pero pronto descubrirá que fisgar en sus archivos secretos no es la mejor idea si uno quiere conservar su trabajo... y su vida.', NULL, '110 minutos', 'https://www.youtube.com/embed/k3TwIJjyjPM', 2),
('Stowaway', 'Una misión al planeta Marte. Dos años de duración. De repente, los tres tripulantes afectados a esta labor deben tomar una decisión imposible cuando un pasajero imprevisto compromete la vida de todos a bordo. No hay vuelta atrás. La decisión deberá tomarse contemplando la vida de los, ahora, cuatro pasajeros aún cuando la supervivecnaia tenga que acarrear algún sacrificio.', NULL, '118 minutos', 'https://www.youtube.com/embed/A_apvQkWsVY', 2),
('Liga de la Justicia - Zack Snyder', 'Decidido a asegurarse de que el sacrificio final de Superman no fue en vano, Bruce Wayne alinea fuerzas con Diana Prince con planes para reclutar un equipo de metahumanos para proteger al mundo de una amenaza de proporciones catastróficas que se aproxima. En esta fascinante entrega, no apta para niños, verás cómo se conforma la Liga de la Justicia, uniendo a los principales superhéroes conocidos como Metahumanos.', NULL, '242 minutos', 'https://www.youtube.com/embed/BUb_-RxsoBs', 2),
('Gravity', 'Durante un paseo espacial rutinario, dos astronautas sufren un grave accidente y quedan flotando en el espacio. Una es la doctora Ryan Stone, una brillante ingeniera en su primera misión espacial en la Shuttle. Su acompañante es el veterano astronauta Matt Kowalsky. Durante el paseo algo sale mal y ocurre el desastre: el shuttle queda destrozado, dejando a Ryan y Matt completamente solos, momento a partir del cual intentarán por todos los medios volver a la Tierra.', NULL, '93 minutos', 'https://www.youtube.com/embed/OiTiKOy59o4', 2),
('It (eso)', 'Remake del clásico de Stephen King, y de la película homónima de 1990, en el que un payaso aterroriza a los niños de un vecindario. En un pequeño pueblo de Maine, siete niños conocidos como el Club de los Perdedores se encuentran cara a cara con problemas de la vida, matones y un monstruo que toma la forma de un payaso llamado Pennywise..', NULL, '135 minutos', 'https://www.youtube.com/embed/FnCdOQsX5kc', 2),
