USE trailerflix;

-- Insertar las categorías.
INSERT INTO categorias (nombre) VALUES
('Serie'),
('Película');

-- Insertar géneros.
INSERT INTO generos (nombre) VALUES
('Sci-Fi'),
('Fantasía'),
('Acción'),
('Drama'),
('Ficción'),
('Sucesos'),
('Misterio'),
('Suceso Real'),
('Crimen'),
('Suspenso'),
('Aventura'),
('Comedia'),
('Familia'),
('Western'),
('Tecnología'),
('Futurista'),
('Terror'),
('Historia'),
('Intriga'),
('¿Ficción?'),
('Ciencia ficción'),
('Romance'),
('Música'),
('Musical'),
('Animación');

-- Insertar actores.
INSERT INTO actores (nombre, apellido) VALUES
('Pedro', 'Pascal'),
('Carl', 'Weathers'),
('Misty', 'Rosas'),
('Chris', 'Bartlett'),
('Rio', 'Hackford'),
('Giancarlo', 'Esposito'),
('Tom', 'Hopper'),
('David', 'Castañeda'),
('Emmy', 'Raver-Lampman'),
('Robert', 'Sheehan'),
('Aidan', 'Gallagher'),
('Elliot', 'Page'),
('Anya', 'Taylor-Joy'),
('Thomas', 'Brodie-Sangster'),
('Harry', 'Melling'),
('Moses', 'Ingram'),
('Chloe', 'Pirrie'),
('Janina', 'Elkin'),
('Lili', 'Reinhart'),
('Casey', 'Cott'),
('Camila', 'Mendes'),
('Marisol', 'Nichols'),
('Madelaine', 'Petsch'),
('Mädchen', 'Amick'),
('Claire', 'Fox'),
('Olivia', 'Colman'),
('Matt', 'Smith'),
('Tobias', 'Menzies'),
('Vanesa', 'Kirby'),
('Helena', 'Bonham Carter'),
('Millie', 'Bobby Brown'), 
('Gaten', 'Matarazzo'),
('Henry', 'Cavill'),
('Sam', 'Claflin'),
('Louis', 'Partridge'),
('Adeel', 'Akhtar'),
('Joaquin', 'Phoenix'),
('Robert', 'De Niro'),
('Zazie', 'Beetz'),
('Frances', 'Conroy'),
('Brett', 'Cullen'),
('Shea', 'Whigham'),
('Robert', 'Downey Jr.'),
('Chris', 'Evans'),
('Mark', 'Ruffalo'),
('Chris', 'Hemsworth'), 
('Jeremy', 'Renner'),
('Emilia', 'Clarke'),
('Lena', 'Headey'),
('Sophie', 'Turner'),
('Kit', 'Harington'),
('Peter', 'Dinklage'),
('Nikolaj', 'Coster-Waldau'),
('Grant', 'Gustin'),
('Carlos', 'Valdes'),
('Danielle', 'Panabaker'),
('Candice', 'Patton'),
('Jesse', 'L. Martin'),
('Tom', 'Cavanagh'),
('Jim', 'Parsons'),
('Johnny', 'Galecki'),
('Kaley', 'Cuoco'),
('Simon', 'Helberg'),
('Kunal', 'Nayyar'),
('Melissa', 'Rauch'),
('Mayim', 'Bialik'),
('Jennifer', 'Aniston'),
('Courteney', 'Cox'),
('Lisa', 'Kudrow'),
('David', 'Schwimmer'),
('Matthew', 'Perry'),
('Matt', 'LeBlanc'),
('Amybeth', 'McNulty'),
('Geraldine', 'James'),
('R. H.', 'Thomson'),
('Corrine', 'Koslo'),
('Dalila', 'Bela'),
('Lucas', 'Jade Zumann'),
('Gillian', 'Anderson'),
('David', 'Duchovny'),
('Mitch', 'Pileggi'),
('Robert', 'Patrick'),
('Tom', 'Braidwood'),
('Bruce', 'Harwood'),
('Jared', 'Harris'),
('Stellan', 'Skarsgård'),
('Emily', 'Watson'),
('Paul', 'Ritter'),
('Jessie', 'Buckley'),
('Adam', 'Nagaitis'),
('Evan', 'Rachel Wood'),
('Thandiwe', 'Newton'),
('Jeffrey', 'Wright'),
('Tessa', 'Thompson'),
('Ed', 'Harris'),
('Luke', 'Hemsworth'),
('Rodrigo', 'Santoro'),
('Simon', 'Quarterman'),
('Clifton', 'Collins Jr.'),
('Anthony', 'Hopkins'),
('Ingrid', 'Bolsø Berdal'),
('Angela', 'Sarafyan'),
('Shannon', 'Woodward'),
('Talulah', 'Riley'),
('Louis', 'Herthum'),
('Ben', 'Barnes'),
('Jimmi', 'Simpson'),
('Leonardo', 'Nam'),
('Aaron', 'Paul'),
('Vincent', 'Cassel'),
('Izabella', 'Alvarez'),
('Jeff', 'Daniel Phillips'),
('Lee', 'Pace'),
('Scoot', 'McNairy'),
('Mackenzie', 'Davis'),
('Kerry', 'Bishé'),
('Toby', 'Huss'),
('Alana', 'Cavanaugh'),
('Jessica', 'Chastain'),
('John', 'Malkovich'),
('Colin', 'Farrell'),
('Geena', 'Davis'),
('Ioan', 'Gruffudd'),
('Margot', 'Robbie'),
('Ewan', 'McGregor'),
('Mary', 'Elizabeth Winstead'),
('Jurnee', 'Smollett'),
('Rosie', 'Perez'),
('Chris', 'Messina'),
('Stacy', 'Martin'),
('Rhona', 'Mitra'),
('Theo', 'James'),
('Peter', 'Ferdinando'),
('Lia', 'Williams'),
('Toby', 'Jones'),
('Miranda', 'Cosgrove'),
('Kate', 'Walsh'),
('Omar', 'Epps'),
('Angus', 'Macfadyen'),
('Jorja', 'Fox'),
('Enver', 'Gjokaj'),
('Bill', 'Skarsgård'),
('Bill', 'Hader'),
('James', 'McAvoy'),
('Isaiah', 'Mustafa'),
('Jay', 'Ryan'),
('Chadwick', 'Boseman'),
('Michael', 'B. Jordan'),
('Lupita', 'Nyong\'o'),
('Danai', 'Gurira'),
('Martin', 'Freeman'),
('Daniel', 'Kaluuya'),
('Christian', 'Bale'),
('Matt', 'Damon'),
('Caitriona', 'Balfe'),
('Josh', 'Lucas'),
('Noah', 'Jupe'),
('Jon', 'Bernthal'),
('Génesis', 'Rodríguez'),
('Vincent', 'Piazza'),
('Benjamin', 'Sokolow'),
('Emily', 'Bayiokos'),
('Amy', 'Manson'),
('Luke', 'Allen-Gale'),
('Nina', 'Bergman'),
('Dominic', 'Mafham'),
('James', 'Weber Brown'),
('Lorina', 'Kamburova'),
('Marion', 'Cotillard'),
('Jude', 'Law'),
('Kate', 'Winslet'),
('Jennifer', 'Ehle'),
('Gwyneth', 'Paltrow'),
('Scarlett', 'Johansson'),
('Florence', 'Pugh'),
('David', 'Harbour'),
('O.T.', 'Fagbenle'),
('Rachel', 'Weisz'),
('William', 'Hurt'),
('Ray', 'Winstone'),
('Kristen', 'Wiig'),
('Jeff', 'Daniels'),
('Michael', 'Peña'),
('Sean', 'Bean'),
('Kate', 'Mara'),
('Alicia', 'Vikander'),
('Domhnall', 'Gleeson'),
('Oscar', 'Isaac'),
('Sonoya', 'Mizuno'),
('Corey', 'Johnson'),
('Claire', 'Selby'),
('Gana', 'Bayarsaikhan'),
('Bryce', 'Dallas Howard'),
('Chris', 'Pratt'),
('Irrfan', 'Khan'),
('Omar', 'Sy'),
('Nick', 'Robinson'),
('Judy', 'Greer'),
('Will', 'Smith'),
('Alice', 'Braga'),
('Charlie', 'Tahan'),
('Dash', 'Mihok'),
('Salli', 'Richardson-Whitfield'),
('Willow', 'Smith'),
('Emma', 'Thompson'),
('Ryan', 'Gosling'),
('Claire', 'Foy'),
('Jason', 'Clarke'),
('Kyle', 'Chandler'),
('Corey', 'Stoll'),
('Patrick', 'Fugit'),
('John', 'Boyega'),
('Scott', 'Eastwood'),
('Cailee', 'Spaeny'),
('Jing', 'Tian'),
('Rinko', 'Kikuchi'),
('Burn', 'Gorman'),
('Ashton', 'Kutcher'),
('Dermot', 'Mulroney'),
('Lukas', 'Haas'),
('Matthew', 'Modine'),
('J.K.', 'Simmons'),
('Lesley', 'Ann Warren'),
('Noah', 'Wyle'),
('Anthony', 'Michael'),
('Joey', 'Slotnick'),
('J.G.', 'Hertzler'),
('Wayne', 'Pére'),
('Sheila', 'Shaw'),
('Gemma', 'Zamprogna'),
('John', 'DiMaggio'),
('Jesse', 'Eisenberg'),
('Andrew', 'Garfield'),
('Justin', 'Timberlake'),
('Armie', 'Hammer'),
('Max', 'Minghella'),
('Rooney', 'Mara'),
('Brenda', 'Song'),
('Rashida', 'Jones'),
('John', 'Gertz'),
('Ryan', 'Phillippe'),
('Rachael', 'Leigh Cook'),
('Tim', 'Robbins'),
('Claire', 'Forlani'),
('Richard', 'Rountree'),
('Tygh', 'Runyan'),
('Ned', 'Bellamy'),
('Tyler', 'Labine'),
('Anna', 'Kendrick'),
('Daniel', 'Dae Kim'),
('Shamier', 'Anderson'),
('Toni', 'Collette'),
('Ben', 'Affleck'),
('Jason', 'Momoa'),
('Ezra', 'Miller'),
('Ray', 'Fisher'),
('Amy', 'Adams'),
('Jeremy', 'Irons'),
('Connie', 'Nielsen'),
('Charlie', 'Sheen'),
('Jon', 'Cryer'),
('Angus T.', 'Jones'),
('Conchata', 'Ferrel'),
('Holland', 'Taylor'),
('Marin', 'Hinkle'),
('Jennifer', 'Bini Taylor'),
('Melanie', 'Lynskey'),
('Amber', 'Tamblyn'),
('Úrsula', 'Corberó'),
('Álvaro', 'Morte'),
('Itziar', 'Ituño'),
('Pedro', 'Alonso'),
('Alba', 'Flores'),
('Miguel', 'Herrán'),
('Jaime', 'Lorente'),
('Esther', 'Acebo'),
('Enrique', 'Arce'),
('Winona', 'Ryder'),
('Finn', 'Wolfhard'),
('Caleb', 'McLaughlin'),
('Natalia', 'Dyer'),
('Charlie', 'Heaton'), 
('Joe', 'Keery'),
('Sandra', 'Bullock'),
('George', 'Clooney'),
('Orto', 'Ignatiussen'), ---
('Phaldut', 'Sharma'),
('Amy', 'Warren'),
('Basher', 'Savage'),
('Adam', 'Cozens'),
('Jaeden', 'Martell'),
('Jeremy', 'Ray'),
('Sophia', 'Lillis'),
('Chosen', 'Jacobs'),
('Jack', 'Dylan Grazer'),
('Wyatt', 'Oleff'),
('Nicholas', 'Hamilton'),
('Tom', 'Hanks'),
('Bill', 'Paxton'),
('Kevin', 'Bacon'),
('Gary', 'Sinise'), ----
('Kathleen', 'Quinlan'),
('Roger', 'Corman'),
('Chris', 'Ellis'),
('Xander', 'Berkeley'),
('Liev', 'Schreiber'),
('Julia', 'Stiles'),
('Seamus', 'Davey-Fitzpatrick'),
('David', 'Thewlis'),
('Pete', 'Postlethwaite'),
('Mia', 'Farrow'),
('Predrag', 'Bjelac'),
('Carlo', 'Sabatini'),
('Amy', 'Huck'),
('Ellen', 'Burstyn'),
('Linda', 'Blair'),
('Max', 'von Sydow'),
('Lee', 'J. Cobb'),
('Kitty', 'Winn'),
('Jack', 'MacGowran'),
('Jason', 'Miller'),
('William', 'O\'Malley'),
('Barton', 'Heyman'),
('Rainn', 'Wilson'),
('Steve', 'Carell'),
('Jenna', 'Fischer'),
('John', 'Krasinski'),
('B.J.', 'Novak'),
('Kate', 'Flannery'),
('Brian', 'Baumgartner'),
('Leslie David', 'Baker'),
('Mindy', 'Kaling'),
('Angela', 'Kinsey'),
('Freddie', 'Highmore'),
('Antonia', 'Thomas'),
('Hill', 'Harper'),
('Richard', 'Schiff'),
('Christina', 'Chang'),
('Paige', 'Spara'),
('Fiona', 'Gubelmann'),
('Will', 'Yun Lee'),
('Nicholas', 'Gonzalez'),
('Eddie', 'Redmayne'),
('Felicity', 'Jones'),
('Charlie', 'Cox'),
('Simon', 'McBurney')
('Maxine', 'Peake'),
('Harry', 'Lloyd'),
('Tom', 'Prior'),
('Benedict', 'Cumberbatch'),
('Keira', 'Knightley'), 
('Taraji P.', 'Henson'),
('Octavia', 'Spencer'),
('Janelle', 'Monáe'),
('Kevin', 'Costner'),
('Kirsten', 'Dunst'),
('Mahershala', 'Ali'),
('Glen', 'Powell'),
('Ariana', 'Neal'), 
('Russell', 'Crowe'),
('Jennifer', 'Connelly'),
('Paul', 'Bettany'),
('Christopher', 'Plummer'),
('Adam', 'Goldberg'),
('Anthony', 'Rapp'),
('Judd', 'Hirsch'),
('Jennifer', 'Lawrence'),
('Michael', 'Sheen'),
('Laurence', 'Fishburne'),
('Andy', 'García'),
('Aurora', 'Perrineau'),
('Kristin', 'Brock'),
('Julee', 'Cerda'),
('Fred', 'Melamed'),
('Anne', 'Hathaway'),
('Andre', 'Braugher'),
('Dianne', 'Wiest'),
('David', 'Morse'),
('William', 'B. Davis'),
('Ryan', 'Robbins'),
('Clea', 'DuVall'),
('Don', 'Thompson'),
('Bryan', 'Cranston'),
('Alan', 'Arkin'),
('John', 'Goodman'),
('Victor', 'Garber'),
('Tate', 'Donovan'),
('Rory', 'Cochrane'),
('Noomi', 'Rapace'),
('Michael', 'Fassbender'),
('Charlize', 'Theron'),
('Logan', 'Marshall-Green'),
('Guy', 'Pearce'),
('Idris', 'Elba'),
('Sean', 'Harris'),
('Rafe', 'Spall'),
('Kate', 'Dickie'),
('Emut', 'Elliott'),
('Benedict', 'Wong'),
('Lucy', 'Hutchinson'),
('Patrick', 'Wilson'),
('Ian', 'Whyte'),
('Branwell', 'Donaghey'),
('Vladimir', 'Furdik'),
('C.C.', 'Smiff'),
('Shane', 'Steyn'),
('John', 'Lebar'),
('Jake', 'Gyllenhaal'),
('Rebecca', 'Ferguson'),
('Ryan', 'Reynolds'),
('Hiroyuki', 'Sanada'),
('Airyon', 'Bakare'),
('Olga', 'Dihovichnaya'),
('Naoko', 'Mori'),
('Haruka', 'Kuroda'),
('Camiel', 'Warren-Taylor'),
('Rosamund', 'Pike'),
('Sam', 'Riley'),
('Aneurin', 'Barnard'),
('Simon', 'Russell Beale'),
('Jonathan', 'Aris'),
('Tim', 'Woodward'),
('Katherine', 'Parkinson'),
('Chris', 'O\'Dowd'),
('Gragam', 'Linehan'),
('Richard', 'Ayoade'),
('Matt', 'Berry'),
('Tom', 'Binns'),
('Lewis', 'Macleod'),
('Noel', 'Fielding'),
('Peter', 'Serafinowicz'),
('Tuppence', 'Middleton'),
('Ian', 'Bonar'),
('Elisabeth', 'Hopper'),
('Nick', 'Bartlett'),
('Wunmi', 'Mosaku'),
('Alex', 'Lawther'),
('Jerome', 'Flynn'),
('Susannah', 'Doyle'),
('Madeline', 'Brewer'),
('Ariane', 'Labed'),
('Sarah', 'Snook'),
('Michael', 'Kelly'),
('Jola', 'Bokinni'),
('Faye', 'Marsay'),
('Ben', 'Wong'),
('Jonas', 'Karlsson'),
('Indira', 'Ainger'),
('James', 'Lance'),
('David', 'Ajala'),
('Sarah', 'Abbott'),
('Clint', 'Dyer'),
('Jake', 'Davies'),
('Letitia', 'Wright'),
('Babs', 'Olusanmokun'),
('Georgina', 'Campbell'),
('Jesse', 'Plemons'),
('Aldis', 'Hodge'),
('Kiran', 'Sonia Sawar'),
('Miley', 'Cyrus'),
('Anthony', 'Mackie'),
('Nicole', 'Beharie'),
('Gugu', 'Mbatha-Raw'),
('Tom', 'Cruise'), 
('Jon', 'Voight'), 
('Emmanuelle', 'Béart'), 
('Henry', 'Czerny'), 
('Jean', 'Reno'), 
('Ving', 'Rhames'), 
('Kristin', 'Scott Thomas'), 
('Vanessa', 'Redgrave'), 
('Ingeborga', 'Dapkünaitè'),
('Elizabeth', 'Debicki'),
('Luca', 'Calvani'),
('Sylvester', 'Groth'),
('Misha', 'Kuznetsov'),
('Hugh', 'Grant'),
('Christian', 'Berkel'),
('Dwayne', 'Johnson'),
('Kevin', 'Hart'),
('Jack', 'Black'),
('Karen', 'Gillan'),
('Nick', 'Jonas'),
('Rhys', 'Darby'),
('Bobby', 'Cannavale'),
('Alex', 'Wolff'),
('Ser\'Darius', 'Blain'),
('Colin', 'Hanks'),
('Madison', 'Iseman'),
('Morgan', 'Turner'),
('Sean', 'Buxton'),
('Mason', 'Guccione'),
('Guy', 'Williams'),
('Marianna', 'Di Martino'), 
('Matthew', 'Goode'),
('Rory', 'Kinnear'),
('Allen', 'Leech'),
('Matthew', 'Beard'),
('Charles', 'Dance'),
('Mark', 'Strong'),
('James', 'Northcote'),
('Gemma', 'Chan'),
('Emily', 'Berrington'),
('Lucy', 'Carless'),
('Colin', 'Morgan'),
('Theo', 'Stevenson'),
('Pixie', 'Daves'),
('Tom', 'Goodman-Hill'),
('Ivanno', 'Jeremiah'),
('Ruth', 'Bradley'),
('Will', 'Tudor'),
('Neil', 'Maskell'),
('Billy', 'Jenkins'),
('Bella', 'Dayne'),
('Thusitha', 'Jayasumdera'),
('Danny', 'Webb'),
('Carrie-Anne', 'Moss'),
('Dominic', 'Cooper'),
('Imogen', 'Poots'),
('Ramón', 'Rodríguez'),
('Michael', 'Keaton'),
('Rami', 'Malek'),
('Kid', 'Cudi'),
('Dakota', 'Johnson'),
('Harrison', 'Gilbertson'),
('Carmela', 'Zumbado'),
('Jalil', 'Jay Lynch'),
('Nick', 'Chinlund'),
('Chad', 'Randall'),
('Julianne', 'Nicholson'),
('Jean', 'Smart'),
('Angourie', 'Rice'),
('Evan', 'Peters'),
('Sosie', 'Bacon'),
('David', 'Denman'),
('Neal', 'Huff'),
('James', 'McArdle'),
('John', 'Douglas Thompson'),
('Joe', 'Tippett'),
('Cameron', 'Mann'),
('Chinasa', 'Ogbuagu'),
('Jamie', 'Foxx'),
('Kerry', 'Washington'),
('Regina', 'King'),
('Harry', 'Lennix'),
('Clifton', 'Powell'),
('Bokeem', 'Woodbine'),
('Sharon', 'Warren'),
('C.J.', 'Sanders'),
('Curtis', 'Armstrong'),
('Michaela', 'Coel'),
('Daniel', 'Lapaine'),
('Hannah', 'John-Kamen'),
('Andrew', 'Roux'),
('Claire', 'Keelan'),
('Sinéad', 'Matthews'),
('Anna', 'Wilson-Jones'),
('Paul', 'Popplewell'),
('Julia', 'Davis'),
('Ashley', 'Thomas'),
('Kerrie', 'Hayes'),
('Amy', 'Beth Hayes'),
('Rebekah', 'Staton'),
('Rhashan', 'Stone'),
('Phoebe', 'Fox'),
('Jimi', 'Mistry'),
('Cherry', 'Jones'),
('Alice', 'Eve'),
('Susannah', 'Fielding'),
('Demetri', 'Goritsas'),
('Kadiff', 'Kirwan'),
('Sope', 'Dirisu'),
('Jackson', 'Bews'),
('Annabel', 'Davis'),
('Billy', 'Griffin Jr.'),
('Paul', 'Lawrence Kitson'),
('Jeff', 'Mash'),
('Patrick', 'Kennedy'),
('Lydia', 'Wilson'),
('Alastair', 'Mackenzie'),
('Chetna', 'Pandya'),
('Nora', 'Lum'),
('Danny','DeVito'),
('Eugene', 'O\'Hare'),
('Danny', 'Glover'),
('Simona', 'Brown'),
('Eve', 'Hewson'),
('Toma', 'Bateman'),
('Robert', 'Aramayo'),
('Tyler', 'Howitt'),
('Georgie', 'Glen'),
('Kamontip', 'Krissy Ashton'),
('Rob', 'Horrocks'),
('Joakim', 'Skarli'),
('Olivia', 'Wilde'),
('Matt', 'Letscher'),
('Portia', 'Doubleday'),
('Spike', 'Jonze'),
('Gal', 'Gadot'),
('Chris', 'Pine'),
('Robin', 'Wright'),
('Lilly', 'Aspell'),
('Amr', 'Waked'),
('Kristoffer', 'Polaha'),
('Jeffrey', 'Tambor'),
('Cynthia', 'Addai-Robinson'),
('John', 'Lithgow'),
('Andy', 'Umberger'),
('Alison', 'Wright'),
('Daeg', 'Faerch'),
('Seth', 'Lee'),
('Tait', 'Fletcher'),
('Angel', 'Giuffria'),
('Ron', 'Yuan'),
('Scott', 'Hunter'),
('Dennis', 'Keiffer'),
('Jake', 'Presley'),
('Hugh', 'Jackman'),
('Allison', 'Janney'),
('Geraldine', 'Viswanathan'),
('Rafael', 'Casal'),
('Stephen', 'Spinella'),
('Annaleigh', 'Ashford'),
('Ray', 'Romano'),
('Hari', 'Dhillon'),
('Jerremy', 'Shamos'),
('Stephanie', 'Kurtzuba'),
('Catherine', 'Curtin'),
('Kathrine', 'Narducci'),
('Ray', 'Abruzzo'),
('Ben', 'Stiller'),
('Robin', 'Williams'),
('Carla', 'Gugino'),
('Dick', 'Van Dyke'),
('Steve', 'Coogan'),
('Jake', 'Cherry'),
('Mickey', 'Rooney'),
('Bill', 'Cobbs'),
('Owen', 'Wilson'),
('Ricky', 'Gervais'),
('Kim', 'Raver'),
('Mizuo', 'Peck'),
('Gwilym', 'Lee'),
('Ben', 'Hardy'),
('Joseph', 'Mazzello'),
('Lucy', 'Boynton'),
('Aidan', 'Gillen'),
('Tom', 'Hollander'),
('Mike', 'Myers'),
('Julianne', 'Hough'),
('Diego', 'Boneta'),
('Alec', 'Baldwin'),
('Russell', 'Brand'),
('Malin', 'Åkerman'),
('Paul', 'Giamatti'),
('Catherine', 'Zeta-Jones'),
('Mary', 'J. Blige'),
('Erica', 'Frene'),
('Shane', 'Hartline'),
('James', 'Martin Kelly'),
('Will', 'Forte'),
('Eli', 'Roth'),
('Joel', 'Courtney'),
('Elle', 'Fanning'),
('Riley', 'Griffiths'),
('Noah', 'Emmerich'),
('AJ', 'Michalka'),
('Ryan', 'Lee'),
('Ron', 'Eldard'),
('Gabriel', 'Basso'),
('Justice', 'Smith'),
('Daniella', 'Pineda'),
('James', 'Cromwell'),
('Ted', 'Levine'),
('Jeff', 'Goldblum'),
('BD', 'Wong'),
('Geraldine', 'Chaplin'),
('Isabella', 'Sermon'),
('Kevin', 'Layne'),
('Harrison', 'Ford'),
('Shia', 'LaBeouf'),
('Cate', 'Blanchett'),
('Karen', 'Allen'),
('John', 'Hurt'),
('Jim', 'Broadbent'),
('Igor', 'Jijikine'),
('Dimitri', 'Diatchenko'),
('Sean', 'Astin'),
('Josh', 'Brolin'),
('Jeff', 'Cohen'),
('Corey', 'Feldman'),
('Kerri', 'Green'),
('Martha', 'Plimpton'),
('Jonathan', 'Ke Quan'),
('John', 'Matuszak'),
('Robert', 'Davi'),
('Bonnie', 'Hunt'),
('Paul', 'Newman'),
('Larry', 'the Cable Guy'),
('Tony', 'Shalhoub'),
('Cheech', 'Marin'),
('Michael', 'Wallis'),
('George', 'Carlin'),
('Paul', 'Dooley'),
('Chris', 'Miller'),
('Tom', 'McGrath'),
('Danny', 'Jacobs'),
('Andy', 'Richter'),
('Nicole', 'Sullivan'),
('Christopher', 'Knights'),
('Wayne', 'Knight'),
('Dale', 'Midkiff'),
('Fred', 'Gwynne'),
('Denise', 'Crosby'),
('Brad', 'Greenquist'),
('Michael', 'Lombard'),
('Miko', 'Hughes'),
('Blaze', 'Berdahl'),
('Susan', 'Blommaert'),
('Mara', 'Clark'),
('Craig T.', 'Nelson'),
('JoBeth', 'Williams'),
('Beatrice', 'Straight'),
('Dominique', 'Dunne'),
('Oliver', 'Robins'),
('Heather', 'O\'Rourke'),
('Michael', 'McManus'),
('Virginia', 'Kiser'),
('Martin', 'Casella'),
('Audrey', 'Tautou'),
('Ian', 'McKellen'),
('Alfred', 'Molina'),
('Jürgen', 'Prochnow'),
('Jean-Yves', 'Berteloot'),
('Etienne', 'Chicot'),
('Rowan', 'Atkinson'),
('Natalie', 'Imbruglia'),
('Ben', 'Miller'),
('Greg', 'Wise'),
('Tasha', 'de Vasconcelos'),
('Douglas', 'McFerran'),
('Steve', 'Nicolson'),
('Terence', 'Harvey'),
('Billy', 'Crudup'),
('Frances', 'McDormand'),
('Kate', 'Hudson'),
('Jason', 'Lee'),
('Zoey', 'Deschanel'),
('Michael', 'Angarano'),
('Anna', 'Paquin'),
('Fairuzza', 'Balk'),
('Joan', 'Cusack'),
('Mike', 'White'),
('Sarah', 'Silverman'),
('Lee', 'Wilkof'),
('Kate', 'McGregor-Stewart'),
('Adam', 'Pascal'),
('Suzzane', 'Douglas'),
('Macaulay', 'Culkin'),
('Joe', 'Pesci'),
('Daniel', 'Stern'),
('John', 'Heard'),
('Catherine', 'O\'Hara'),
('Roberts', 'Blossom'),
('Devin', 'Ratray'),
('Michael C.', 'Maronna'),
('Hillary', 'Wolf'),
('Vince', 'Vaughn'),
('Will', 'Ferrell'),
('Rose', 'Byrne'),
('Aasif', 'Mandvi'),
('Josh', 'Brener'),
('Dylan', 'O\'Brien'),
('Tiya', 'Sircar'),
('Tobit', 'Raphael'),
('Josh', 'Gad'),
('Jessica', 'Szohr'),
('Rob', 'Riggle'),
('Eric', 'André'),
('Harvey', 'Guillén'),
('Gary', 'Anthony Williams'),
('Bruno', 'Amato'),
('Karen', 'Ceesay'),
('Rebecca', 'Hazlewood'),
('Sacha', 'Dhawan'),
('Diedrich', 'Bader'),
('Pippa', 'Black'),
('Parvesh', 'Ceena'),
('Thushari', 'Jayasekera'),
('Ben', 'Rappaport'),
('Guru', 'Singh'),
('Rizwan', 'Manji'),
('Anisha', 'Nagarajan'),
('Carla', 'Gallo'),
('Radhika', 'Chaudhari'),
('Nicholas', 'Logan'),
('Blake', 'Lively'),
('Óscar', 'Jaenada'),
('Janelle', 'Bailley'),
('Chelsea', 'Moody'),
('Angelo Josue', 'Lozano Corzo'),
('José Manuel', 'Trujillo Salas'),
('Sedona', 'Legge'),
('Pablo', 'Calva'),
('Jogn', 'Hawkes'),
('Sam', 'Worthington'),
('Martin', 'Henderson'),
('Thomas M.', 'Wright'),
('Clive', 'Standen'),
('Mia', 'Goth'),
('Raúl', 'Juliá'),
('Anjelica', 'Huston'),
('Christopher', 'Lloyd'),
('Christina', 'Ricci'),
('Carel', 'Struycken'),
('Dan', 'Hedaya'),
('Jimmy', 'Workman'),
('Elizabeth', 'Wilson'),
('Dana', 'Ivey');

-- Insertar contenido series: idCategoria = 1.
INSERT INTO contenido (titulo, resumen, temporadas, duracion, trailer, idCategoria) VALUES 
('The Mandalorian', 'Ambientada tras la caída del Imperio y antes de la aparición de la Primera Orden, la Serie sigue los pasos de un pistolero solitario en las aventuras que protagoniza en los confines de la galaxia, donde no alcanza la autoridad de la Nueva República.', 2, NULL, 'https://www.youtube.com/embed/aOC8E8z_ifw', 1), 
('The Umbrella Academy', 'La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.', 1, NULL, 'https://www.youtube.com/embed/KHucKOK-Vik', 1),
('Gambito de Dama', 'En los cincuenta, una joven de un orfanato descubre que tiene un increíble don para el ajedrez y recorre el arduo camino a la fama mientras lucha contra las adicciones.', 1, NULL, 'https://www.youtube.com/embed/lbleRbyGKL4', 1),
('Riverdale', 'El paso a la edad adulta incluye sexo, romance, escuela y familia. Para Archie y sus amigos, también hay misterios oscuros.', 5, NULL, 'https://www.youtube.com/embed/HxtLlByaYTc', 1),
('The Crown', 'Este drama narra las rivalidades políticas y el romance de la reina Isabel II, así como los sucesos que moldearon la segunda mitad del siglo XX.', 4, NULL, 'https://www.youtube.com/embed/JWtnJjn6ng0', 1),
('Juego de tronos', 'En un mundo fantástico y en un contexto medieval varias familias, relativas a la nobleza, se disputan el poder para dominar el territorio ficticio de Poniente (Westeros) y tomar el control de los Siete Reinos desde el Trono de Hierro, lugar donde el rey ejerce el poder.', 8, NULL, 'https://www.youtube.com/embed/KPLWWIOCOOQ', 1),
('The Flash', 'Sigue las veloces aventuras de Barry Allen, un joven común y corriente con el deseo latente de ayudar a los demás. Cuando una inesperada partícula aceleradora golpea por accidente a Barry, de pronto se encuentra cargado de un increíble poder para moverse a increíbles velocidades. Mientras Barry siempre ha tenido el alma de un héroe, sus nuevos poderes le han dado la capacidad de actuar como tal.', 6, NULL, 'https://www.youtube.com/embed/Yj0l7iGKh8g', 1),
('The Big Bang Theory', 'Leonard y Sheldon son dos físicos que comparten trabajo y apartamento. La Serie comienza con la mudanza de Penny, su nueva y atractiva vecina, y hace hincapié en la dificultad de los físicos para relacionarse con personas fuera de su entorno para dar lugar a situaciones cómicas.', 12, NULL, 'https://www.youtube.com/embed/WBb3fojgW0Q', 1),
('Friends', 'Friends narra las aventuras y desventuras de seis jóvenes de Nueva York: Rachel, Monica, Phoebe, Ross, Chandler y Joey. Ellos forman una unida pandilla de amigos que viven en Manhattan y que suelen reunirse en sus apartamentos o en su bar habitual cafetería, el Central Perk. A pesar de los numerosos cambios que se producen en sus vidas, su amistad es inquebrantable en la dura batalla por salir adelante en sus periplos profesionales y personales.', 10, NULL, 'https://www.youtube.com/embed/ekYGfU0XIx0', 1),
('Anne with an E', 'Anne Shirley es una niña huérfana que vive en un pequeño pueblo llamado Avonlea que pertenece a la Isla del Príncipe Eduardo, en el año 1890. Después de una infancia difícil, donde fue pasando de orfanato a hogares de acogida, es enviada por error a vivir con una solterona y su hermano. Cuando cumple 13 años, Anne va a conseguir transformar su vida y el pequeño pueblo donde vive gracias a su fuerte personalidad, intelecto e imaginación. Basada en la inolvidable novela.', 2, NULL, 'https://www.youtube.com/embed/M4T-_aB8smU', 1),
('Expedientes Secretos X', 'Fox Mulder y Dana Scully son dos investigadores del FBI que investigan casos sin resolución ni explicación, ya sea por razones paranormales (espíritus, criaturas extrañas, aliens...) ya porque el gobierno se ha encargado de ocultar todo tipo de pruebas. Cuando Mulder tenía doce años, su hermana pequeña fue secuestrada por unos desconocidos, aunque él cree que, en realidad, fue abducida por extraterrestres. Tras acabar sus estudios en la universidad de Oxford, ingresó en la Academia de Quantico, donde se ganó el apodo de 'siniestro'', 11, NULL, 'https://www.youtube.com/embed/KKziOmsJxzE', 1),
('Chernobyl', 'Sigue «la verdadera historia de una de las peores catástrofes provocadas por el hombre y habla de los valientes hombres y mujeres que se sacrificaron para salvar a Europa de un desastre inimaginable. La miniSerie se centra en el desgarrador alcance del desastre de la planta nuclear que ocurrió en Ucrania en abril de 1986, revelando cómo y por qué ocurrió, además contando las sorprendentes y notables historias de los héroes que lucharon y cayeron.', 1, NULL, 'https://www.youtube.com/embed/s9APLXM9Ei8', 1),
('Westworld', 'Westworld es una oscura odisea acerca del amanecer de la conciencia artificial y la evolución del pecado. Situada en la intersección del futuro cercano y el pasado reimaginado, explora un mundo donde cada apetito humano, sin importar cuán noble o depravado, puede ser saciado. Está ambientada en un parque temático futurista dirigido por el Dr. Robert Ford (Anthony Hopkins). Las instalaciones cuentan con androides caracterizados del western americano, y gracias a ellos los visitantes pueden introducirse en cualquier tipo de fantasía por muy oscura que sea.', 3, NULL, 'https://www.youtube.com/embed/qLFBcdd6Qw0', 1),
('Halt and Catch Fire', 'Situada en los inicios de la década de 1980, un visionario ficticio, un ingeniero electrónico y una prodigiosa ingeniera, se alían a una programadora de software para confrontar con las corporaciones informáticas dominantes de la época. El Personal de la firma y sus socios de negocio, comenzarán una carrera que cambiará la cultura en el Estado de Texas, cuna de las empresas de tecnología, casi de la misma forma que lo es hoy Silicon Valey. \n Esta historia ficticia emula el trabajo realizado, en su momento, por la firma Compaq, cuando clonó el BIOS de las Computadoras Personales IBM, dando vida así al económico mercado de los clones. Mostrando también, a lo largo de sus 4 temporadas, el nacimiento de la arquitectura abierta de hardware, los videojuegos online, las salas de chat y de trueque de productos físicos, los BBS, y las primeras nubes computacionales, hasta la llegada de Internet (sin dejar afuera la guerra de los web browsers).', 4, NULL, 'https://www.youtube.com/embed/pWrioRji60A', 1),
('Two and a half men', 'Un quiropráctico y padre soltero, Alan Harper, vive en una casa al frente de la playa con su hijo mediocre, Jake, y un billonario de la Internet divorciado Walden Schmidt, que se muda con la familia de los Harper y ofrece comprar la casa luego de la muerte inesperada del hermano de Alan, Charlie, que era el propietario de la casa en la que vivía con Alan y Jake, luego de que padre e hijo se mudaran después del divorcio de Alan. La exesposa de Alan y madre de Jake, Judith, permanece en sus vidas.', 12, NULL, 'https://www.youtube.com/embed/mVHDanSl2pc', 1),
('La casa de Papel', 'Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.', 4, NULL, 'https://www.youtube.com/embed/w1jkStuRQU8', 1),
('Stranger Things', 'Pasan cosas muy extrañas en Hawkins, Indiana, tras una desaparición que revela la presencia de una niña con poderes sobrenaturales. Después de la extraña desaparición de un niño, un pueblo se encuentra ante un misterio que revela experimentos secretos, fuerzas sobrenaturales.', 4, NULL, 'https://www.youtube.com/embed/b9EkMc79ZSU', 1),
('The Office', 'Steve Carell protagoniza The Office, un fresco y divertido vistazo, con formato pseudo-documental, al día a día en la vida de unos excéntricos trabajadores de la empresa Dunder Mifflin. El serio pero despistadísimo director Michael Scott se considera un magnífico jefe y mentor, pero realmente inspira más críticas que respeto a sus empleados.', 9, NULL, 'https://www.youtube.com/embed/LHOtME2DL4g', 1),
('The Good Doctor', 'Un cirujano joven y autista que padece el síndrome del sabio empieza a trabajar en un hospital prestigioso. Allá tendrá que vencer el escepticismo con el que sus colegas lo reciben.', 4, NULL, 'https://www.youtube.com/embed/fYlZDTru55g', 1),
('The IT Crowd', 'En un desordenado sótano en las entrañas de Industrias Reynholm habitan Roy y Moss, los componentes del Departamento de informática. Víctimas del desprecio y del escarnio de sus compañeros más guays, su mundo de servidores y cortafuegos se ve interrumpido por la llegada de Jen, su nueva jefa, que sabe tanto de ordenadores como un yak.', 4, NULL, 'https://www.youtube.com/embed/wCa1jfo93jQ', 1),
('Humans', 'En un presente paralelo donde el último gadget que hay que tener para cualquier familia ocupada es un 'Synth' - un sirviente robótico altamente desarrollado que es tan similar a un humano real que está transformando la manera en que vivimos.', 3, NULL, 'https://www.youtube.com/embed/BV8qFeZxZPE', 1),
('Mare of Easttown', 'Mare of Easttown es una miniserie estadounidense de drama y misterio creada por Brad Ingelsby cuenta la historia de Mare Sheehan, una detective de un pequeño pueblo de Pensilvania que investiga un asesinato local mientras trata de evitar que su vida se desmorone a raiz de la muerte de su hijo, su separación, y la posible restitución de su nieto a su madre biológica.', 1, NULL, 'https://www.youtube.com/embed/miQqyfO66uw', 1),
('Black Mirror', 'Black Mirror es una serie de televisión británica creada por Charlie Brooker que muestra el lado oscuro de la vida y la tecnología. La serie es producida por Zeppotron para Endemol. En cuanto al contenido del programa y la estructura, Brooker ha señalado que 'cada episodio tiene un tono diferente, un entorno diferente, incluso una realidad diferente, pero todos son acerca de la forma en que vivimos ahora - y la forma en que podríamos estar viviendo en 10 minutos si somos torpes'.', 5, NULL, 'https://www.youtube.com/embed/jVHCQfcugdw', 1),
('Detrás de sus ojos', 'Una madre soltera se adentra en un mundo de retorcidos juegos psicológicos cuando inicia una relación cuasi-no consentida con su jefe, un psiquiatra, y se hace amiga en secreto de su misteriosa esposa. La trama se bassa en un thriller sobre un triángulo amoroso perverso, más la introducción sutilmente de un elemento clave, que dará un giro notable a la obra.', 1, NULL, 'https://www.youtube.com/embed/c4LtoWQaLxk', 1),
('Outsourced', 'Ambientada en el continente estadounidense, una empresa norteamericana que busca reducir los gastos, asciende a su mejor empleado del Call Center, poniéndolo a cargo del mismo. La única condición para dicho empleado, es viajar a la India, lugar en el mundo donde tercerizan el servicio ode atención al cliente, para abaratar costos. Allí, en la Ciudad de Bombay, los nativos le explican la cultura indú a los nóveles norteamericanos, y viceversa. Tendrán que convivir cada uno de los empleados de estos diferentes países, con sus pares y/o jefes opuestos en cultura.', 1, NULL, 'https://www.youtube.com/embed/_wR3LhFlgGo', 1);
